name: ubuntu-raspi2-kernel
version: 4.4.0
summary: The Raspberry Pi 2/3 kernel for snappy
description: This is a snapped kernel, based off the xenial raspi2 branch and config
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kdefconfig: ['--makefile=debian/snapcraft.mk', 'branch=raspi2','flavour=raspi2', 'config']
    kconfigs:
      - CONFIG_LOCALVERSION="-xenial_raspi2"
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib
    build-packages:
      - cpio
      - libssl-dev
      - dpkg-dev
    kernel-image-target: zImage
