#!/bin/bash

REPO=https://github.com/Broadcom-Switch/OpenNSL

O=OpenNSL
SDK=$O/sdk-6.5.6-gpl-modules
S=$SDK/systems

#
# Must be run from the root of the Xenial 4.4 tree.
#
if ! egrep -q "Blurry Fish Butt" Makefile
then
	echo This script must be run from the root of the source tree.
	exit 1
fi

# Fetch OpenNSL from its repository and drop it into this source tree.

if [ ! -d $O ]
then
	git clone --depth 1 $REPO $O
fi

mkdir -p ubuntu/opennsl/$O
rsync -av --delete --exclude=.git $O/ ubuntu/opennsl/$O/
rm -rf ubuntu/opennsl/$O/bin

#
# You must visually inspect for new files
#
git add -f ubuntu/opennsl/$O
git add -u

cd $O
V="`git log -1 --pretty=oneline|while read c m;do echo $m;done`"
cd ..

echo git commit -m\"UBUNTU: Update $O to ${V}\"

