OpenNSL API Guide and Reference Manual: examples/example_rm.c File Reference
example_rm.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <opennsl/types.h>
#include <opennsl/error.h>
#include <opennsl/l2.h>
#include <examples/util.h>
#include <opennsl/rmapi.h>
Macros
#define DEFAULT_RM_CLIENTID 0
#define DEFAULT_UNIT 0
#define EXAMPLE_RM_PORT_PBMP_FORMAT "%08X %08X %08X %08X %08X %08X %08X %08X"
#define EXAMPLE_RM_PORT_PBMP_SHOW(pbmp)
Functions
int _opennsl_l2_traverse_cb (int unit, opennsl_l2_addr_t *info, void *user_data)
Callback function to show L2 table information.
int example_l2_params_get (uint16 *vlan, int *port, opennsl_mac_t mac)
Utility function to take L2 parameters from the user.
void example_rm_show_profile (opennsl_rm_profile_t *profile)
Display the RM profile parameters of a registered client.
int main (int argc, char *argv[])
Main function for RM functionality testing application.
Variables
char example_usage []
Macro Definition Documentation
#define DEFAULT_RM_CLIENTID 0
Definition at line 47 of file example_rm.c.
Referenced by main().
#define DEFAULT_UNIT 0
Definition at line 46 of file example_rm.c.
Referenced by main().
#define EXAMPLE_RM_PORT_PBMP_FORMAT "%08X %08X %08X %08X %08X %08X %08X %08X"
Definition at line 35 of file example_rm.c.
Referenced by example_rm_show_profile().
#define EXAMPLE_RM_PORT_PBMP_SHOW (pbmp)
Value:
_SHR_PBMP_WORD_GET(pbmp,7), \
                             _SHR_PBMP_WORD_GET(pbmp,6), \
                             _SHR_PBMP_WORD_GET(pbmp,5), \
                             _SHR_PBMP_WORD_GET(pbmp,4), \
                             _SHR_PBMP_WORD_GET(pbmp,3), \
                             _SHR_PBMP_WORD_GET(pbmp,2), \
                             _SHR_PBMP_WORD_GET(pbmp,1), \
                             _SHR_PBMP_WORD_GET(pbmp,0)
Definition at line 36 of file example_rm.c.
Referenced by example_rm_show_profile().
Function Documentation
int _opennsl_l2_traverse_cb (int unit, opennsl_l2_addr_t * info, void * user_data)
Callback function to show L2 table information.
Parameters
unit [IN] unit number
info [IN] L2 address structure
*user_data [IN] User specified cookie
Returns
OPENNSL_E_NONE
Definition at line 69 of file example_rm.c.
References opennsl_l2_addr_s::mac, OPENNSL_E_NONE, opennsl_l2_addr_s::port, and opennsl_l2_addr_s::vid.
int example_l2_params_get (uint16 * vlan, int * port, opennsl_mac_t mac)
Utility function to take L2 parameters from the user.
Parameters
unit [IN] unit number
vlan [IN] VLAN identifier
port [IN] port number
mac [IN] MAC address
Returns
OPENNSL_E_NONE
Definition at line 91 of file example_rm.c.
References example_read_user_choice(), example_read_user_string(), NULL, OPENNSL_E_FAIL, OPENNSL_E_NONE, and opennsl_mac_parse().
Referenced by main().
void example_rm_show_profile (opennsl_rm_profile_t * profile)
Display the RM profile parameters of a registered client.
Parameters
profile [IN] RM profile structure pointer
Returns
None
Definition at line 135 of file example_rm.c.
References _SHR_BITDCLSIZE, EXAMPLE_RM_PORT_PBMP_FORMAT, EXAMPLE_RM_PORT_PBMP_SHOW, OPENNSL_VLAN_COUNT, opennsl_rm_profile_s::port_bitmap, RM_MAX_UNITS, and opennsl_rm_profile_s::vlan_bitmap.
Referenced by main().
int main (int argc, char * argv[])
Main function for RM functionality testing application.
Parameters
argc,argv commands line arguments
Returns
OPENNSL_E_XXX OpenNSL API return code
Definition at line 165 of file example_rm.c.
References _opennsl_l2_traverse_cb(), DEFAULT_RM_CLIENTID, DEFAULT_UNIT, example_l2_params_get(), example_port_default_config(), example_read_user_choice(), example_rm_show_profile(), example_usage, opennsl_l2_addr_s::flags, NULL, opennsl_driver_init(), OPENNSL_E_NONE, OPENNSL_E_PARAM, opennsl_errmsg, OPENNSL_GPORT_MODPORT_SET, opennsl_l2_addr_add(), opennsl_l2_addr_delete(), opennsl_l2_addr_get(), opennsl_l2_addr_t_init(), OPENNSL_L2_STATIC, opennsl_l2_traverse(), OPENNSL_PBMP_CLEAR, OPENNSL_PBMP_PORT_ADD, OPENNSL_RM_E_NONE, opennsl_rm_profile_get(), opennsl_rm_profile_ports_update(), opennsl_rm_profile_vlans_update(), OPENNSL_VLAN_VEC_SET, OPENNSL_VLAN_VEC_ZERO, opennsl_l2_addr_s::port, port(), and opennsl_l2_addr_s::vid.
Variable Documentation
char example_usage[]
Initial value:
=
"Syntax: example_rm                                                    \n\r"
"                                                                      \n\r"
"Paramaters: None.                                                     \n\r"
"                                                                      \n\r"
"Example: The following command is used to start the                   \n\r"
"resource manager test application.                                    \n\r"
"         example_rm                                                   \n\r"
"                                                                      \n\r"
"Usage Guidelines: None.                                               \n\r"
Definition at line 49 of file example_rm.c.