OpenNSL API Guide and Reference Manual: examples/xgs/example_bst.c File Reference
example_bst.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <opennsl/init.h>
#include <opennsl/error.h>
#include <opennsl/cosq.h>
#include <opennsl/vlan.h>
#include <opennsl/switch.h>
#include <sal/driver.h>
#include <examples/util.h>
Data Structures
struct example_bst_counter_t
Macros
#define _BRCM_56960_DEVICE_ID 0xb960
#define _BRCM_IS_CHIP_TH(_info) (((_info).device == _BRCM_56960_DEVICE_ID))
#define _BST_STAT_ID_CPU opennslBstStatIdCpuQueue
#define _BST_STAT_ID_DEVICE opennslBstStatIdDevice
#define _BST_STAT_ID_EGR_MCAST_POOL opennslBstStatIdEgrMCastPool
#define _BST_STAT_ID_EGR_POOL opennslBstStatIdEgrPool
#define _BST_STAT_ID_EGR_PORT_SHARED opennslBstStatIdEgrPortPoolSharedMcast
#define _BST_STAT_ID_EGR_UCAST_PORT_SHARED opennslBstStatIdEgrPortPoolSharedUcast
#define _BST_STAT_ID_ING_POOL opennslBstStatIdIngPool
#define _BST_STAT_ID_MAX_COUNT opennslBstStatIdMaxCount
#define _BST_STAT_ID_MCAST opennslBstStatIdMcast
#define _BST_STAT_ID_PORT_POOL opennslBstStatIdPortPool
#define _BST_STAT_ID_PRI_GROUP_HEADROOM opennslBstStatIdPriGroupHeadroom
#define _BST_STAT_ID_PRI_GROUP_SHARED opennslBstStatIdPriGroupShared
#define _BST_STAT_ID_RQE_POOL opennslBstStatIdRQEPool
#define _BST_STAT_ID_RQE_QUEUE opennslBstStatIdRQEQueue
#define _BST_STAT_ID_UCAST opennslBstStatIdUcast
#define _BST_STAT_ID_UCAST_GROUP opennslBstStatIdUcastGroup
#define DEFAULT_UNIT 0
#define DEFAULT_VLAN 1
#define MAX_COSQ_COUNT 8
#define MAX_COUNTERS 4
#define MAX_DIGITS_IN_CHOICE 5
Functions
int example_bst_default_profile_set (int unit)
To set the default BST profiles.
void example_bst_trigger_callback (int unit, opennsl_switch_event_t event, uint32 bid, uint32 port, uint32 cosq, void *cookie)
Callback function to capture BST triggers.
int main (int argc, char *argv[])
Main function for bst sample application.
Variables
char example_usage []
Macro Definition Documentation
#define _BRCM_56960_DEVICE_ID 0xb960
Definition at line 81 of file example_bst.c.
#define _BRCM_IS_CHIP_TH (_info) (((_info).device == _BRCM_56960_DEVICE_ID))
Definition at line 83 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_CPU opennslBstStatIdCpuQueue
Definition at line 78 of file example_bst.c.
#define _BST_STAT_ID_DEVICE opennslBstStatIdDevice
Definition at line 64 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_EGR_MCAST_POOL opennslBstStatIdEgrMCastPool
Definition at line 66 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_EGR_POOL opennslBstStatIdEgrPool
Definition at line 65 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_EGR_PORT_SHARED opennslBstStatIdEgrPortPoolSharedMcast
Definition at line 74 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_EGR_UCAST_PORT_SHARED opennslBstStatIdEgrPortPoolSharedUcast
Definition at line 73 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_ING_POOL opennslBstStatIdIngPool
Definition at line 67 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_MAX_COUNT opennslBstStatIdMaxCount
Definition at line 79 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_MCAST opennslBstStatIdMcast
Definition at line 72 of file example_bst.c.
Referenced by example_bst_default_profile_set(), and main().
#define _BST_STAT_ID_PORT_POOL opennslBstStatIdPortPool
Definition at line 68 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_PRI_GROUP_HEADROOM opennslBstStatIdPriGroupHeadroom
Definition at line 70 of file example_bst.c.
Referenced by example_bst_default_profile_set(), and main().
#define _BST_STAT_ID_PRI_GROUP_SHARED opennslBstStatIdPriGroupShared
Definition at line 69 of file example_bst.c.
Referenced by example_bst_default_profile_set(), and main().
#define _BST_STAT_ID_RQE_POOL opennslBstStatIdRQEPool
Definition at line 76 of file example_bst.c.
#define _BST_STAT_ID_RQE_QUEUE opennslBstStatIdRQEQueue
Definition at line 75 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define _BST_STAT_ID_UCAST opennslBstStatIdUcast
Definition at line 71 of file example_bst.c.
Referenced by example_bst_default_profile_set(), and main().
#define _BST_STAT_ID_UCAST_GROUP opennslBstStatIdUcastGroup
Definition at line 77 of file example_bst.c.
Referenced by example_bst_default_profile_set().
#define DEFAULT_UNIT 0
Definition at line 42 of file example_bst.c.
Referenced by main().
#define DEFAULT_VLAN 1
Definition at line 39 of file example_bst.c.
#define MAX_COSQ_COUNT 8
Definition at line 41 of file example_bst.c.
Referenced by main().
#define MAX_COUNTERS 4
Definition at line 40 of file example_bst.c.
Referenced by main().
#define MAX_DIGITS_IN_CHOICE 5
Definition at line 43 of file example_bst.c.
Function Documentation
int example_bst_default_profile_set (int unit)
To set the default BST profiles.
Parameters
unit [IN] Unit number
Returns
None
Remarks
None
Definition at line 94 of file example_bst.c.
References _BRCM_IS_CHIP_TH, _BST_STAT_ID_DEVICE, _BST_STAT_ID_EGR_MCAST_POOL, _BST_STAT_ID_EGR_POOL, _BST_STAT_ID_EGR_PORT_SHARED, _BST_STAT_ID_EGR_UCAST_PORT_SHARED, _BST_STAT_ID_ING_POOL, _BST_STAT_ID_MAX_COUNT, _BST_STAT_ID_MCAST, _BST_STAT_ID_PORT_POOL, _BST_STAT_ID_PRI_GROUP_HEADROOM, _BST_STAT_ID_PRI_GROUP_SHARED, _BST_STAT_ID_RQE_QUEUE, _BST_STAT_ID_UCAST, _BST_STAT_ID_UCAST_GROUP, opennsl_cosq_bst_profile_s::byte, opennsl_port_config_s::e, opennsl_cosq_bst_profile_set(), OPENNSL_E_NONE, opennsl_errmsg, opennsl_info_get(), OPENNSL_PBMP_ITER, opennsl_port_config_get(), opennsl_port_gport_get(), and port().
Referenced by main().
void example_bst_trigger_callback (int unit, opennsl_switch_event_t event, uint32 bid, uint32 port, uint32 cosq, void * cookie)
Callback function to capture BST triggers.
Parameters
unit [IN] Unit number
event [IN] BST event
bid [IN] BST ID
port [IN] Port number
cosq [IN] COS queue
cookie [IN] To hold the data from register function
Returns
None
Definition at line 254 of file example_bst.c.
Referenced by main().
int main (int argc, char * argv[])
Main function for bst sample application.
Parameters
argc,argv commands line arguments
Returns
OPENNSL_E_XXX OpenNSL API return code
Definition at line 271 of file example_bst.c.
References _BST_STAT_ID_MCAST, _BST_STAT_ID_PRI_GROUP_HEADROOM, _BST_STAT_ID_PRI_GROUP_SHARED, _BST_STAT_ID_UCAST, DEFAULT_UNIT, example_bst_default_profile_set(), example_bst_trigger_callback(), example_port_default_config(), example_read_user_choice(), example_switch_default_vlan_config(), example_usage, MAX_COSQ_COUNT, MAX_COUNTERS, NULL, opennsl_cosq_bst_stat_clear(), opennsl_cosq_bst_stat_get(), opennsl_cosq_bst_stat_sync(), opennsl_driver_init(), OPENNSL_E_NONE, OPENNSL_E_PARAM, opennsl_errmsg, opennsl_port_gport_get(), opennsl_switch_control_set(), opennsl_switch_event_register(), opennslSwitchBstEnable, and port().
Variable Documentation
char example_usage[]
Initial value:
=
"Syntax: example_bst                                                   \n\r"
"                                                                      \n\r"
"Paramaters: None                                                      \n\r"
"                                                                      \n\r"
"Example: The following command is used to see the bst stats of a port \n\r"
"         example_bst                                                  \n\r"
"                                                                      \n\r"
"Usage Guidelines: This program request the user to enter the port     \n\r"
"                  number interactively                                \n\r"
Definition at line 45 of file example_bst.c.