OpenNSL API Guide and Reference Manual: examples/xgs/example_rpc_client.c File Reference
example_rpc_client.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <opennsl/error.h>
#include <opennsl/types.h>
#include <examples/util.h>
#include <cJSON.h>
#include <examples/rpc_utils.h>
Functions
int main (int argc, char *argv[])
int process_response (char *buffer, int length, int api_id)
Function Documentation
int main (int argc, char * argv[])
Definition at line 255 of file example_rpc_client.c.
References DEF_SERVER, EXAMPLE_CONFIG_PORT, example_read_user_choice(), OPENNSL_E_NONE, process_response(), and RPC_MAX_BUFFER_LEN.
int process_response (char * buffer, int length, int api_id)
Definition at line 39 of file example_rpc_client.c.
References JSON_COMPARE_STRINGS_AND_CLEANUP, JSON_MAX_NODE_LENGTH, JSON_VALIDATE_JSON_AS_NUMBER, JSON_VALIDATE_JSON_AS_STRING, JSON_VALIDATE_JSON_POINTER, and NULL.
Referenced by main().