OpenNSL API Guide and Reference Manual: examples/xgs/example_rpc_app.c File Reference
example_rpc_app.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <opennsl/types.h>
#include <opennsl/error.h>
#include <opennsl/init.h>
#include <opennsl/port.h>
#include <sal/driver.h>
Functions
int main (int argc, char *argv[])
Main function for OpenNSL RPC client functionality testing application.
Variables
char example_usage []
Function Documentation
int main (int argc, char * argv[])
Main function for OpenNSL RPC client functionality testing application.
Parameters
argc,argv commands line arguments
Returns
OPENNSL_E_XXX OpenNSL API return code
Definition at line 54 of file example_rpc_app.c.
References opennsl_port_config_s::all, opennsl_port_config_s::ce, opennsl_port_config_s::cpu, opennsl_info_s::device, example_usage, opennsl_port_config_s::ge, NULL, opennsl_attach_max(), opennsl_driver_init(), OPENNSL_E_NONE, OPENNSL_E_PARAM, opennsl_info_get(), opennsl_port_config_get(), opennsl_port_gport_get(), _shr_pbmp::pbits, opennsl_port_config_s::port, opennsl_info_s::revision, and opennsl_port_config_s::xe.
Variable Documentation
char example_usage[]
Initial value:
=
"Syntax: example_rpc_app                                               \n\r"
"                                                                      \n\r"
"Paramaters: None.                                                     \n\r"
"                                                                      \n\r"
"Example: The following command is used to start the                   \n\r"
"opennsl RPC application.                                              \n\r"
"         example_rpc_app                                              \n\r"
"                                                                      \n\r"
"Usage Guidelines: None.                                               \n\r"
Definition at line 34 of file example_rpc_app.c.