OpenNSL API Guide and Reference Manual: examples/example_stat.c File Reference
example_stat.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sal/driver.h>
#include <opennsl/error.h>
#include <opennsl/stat.h>
#include <opennsl/vlan.h>
#include <examples/util.h>
Macros
#define DEFAULT_UNIT 0
#define DEFAULT_VLAN 1
#define MAX_COUNTERS 30
#define MAX_DIGITS_IN_CHOICE 5
Functions
int main (int argc, char *argv[])
Main function for statistics sample application.
Variables
char example_usage []
Macro Definition Documentation
#define DEFAULT_UNIT 0
Definition at line 38 of file example_stat.c.
Referenced by main().
#define DEFAULT_VLAN 1
Definition at line 39 of file example_stat.c.
#define MAX_COUNTERS 30
Definition at line 40 of file example_stat.c.
Referenced by main().
#define MAX_DIGITS_IN_CHOICE 5
Definition at line 41 of file example_stat.c.
Function Documentation
int main (int argc, char * argv[])
Main function for statistics sample application.
Parameters
argc,argv commands line arguments
Returns
OPENNSL_E_XXX OpenNSL API return code
Definition at line 62 of file example_stat.c.
References DEFAULT_UNIT, example_port_default_config(), example_read_user_choice(), example_switch_default_vlan_config(), example_usage, MAX_COUNTERS, NULL, opennsl_driver_init(), OPENNSL_E_NONE, OPENNSL_E_PARAM, OPENNSL_E_UNAVAIL, opennsl_errmsg, opennsl_spl_snmpIfInBroadcastPkts, opennsl_spl_snmpIfInDiscards, opennsl_spl_snmpIfInErrors, opennsl_spl_snmpIfInMulticastPkts, opennsl_spl_snmpIfInNUcastPkts, opennsl_spl_snmpIfInUcastPkts, opennsl_spl_snmpIfOutBroadcastPkts, opennsl_spl_snmpIfOutDiscards, opennsl_spl_snmpIfOutErrors, opennsl_spl_snmpIfOutMulticastPkts, opennsl_spl_snmpIfOutNUcastPkts, opennsl_spl_snmpIfOutUcastPkts, opennsl_stat_clear(), opennsl_stat_get(), opennsl_stat_init(), opennsl_stat_multi_get(), opennsl_stat_sync(), port(), snmpOpenNSLReceivedPkts1024to1518Octets, snmpOpenNSLReceivedPkts128to255Octets, snmpOpenNSLReceivedPkts1519to2047Octets, snmpOpenNSLReceivedPkts2048to4095Octets, snmpOpenNSLReceivedPkts256to511Octets, snmpOpenNSLReceivedPkts4095to9216Octets, snmpOpenNSLReceivedPkts512to1023Octets, snmpOpenNSLReceivedPkts64Octets, snmpOpenNSLReceivedPkts65to127Octets, snmpOpenNSLTransmittedPkts1024to1518Octets, snmpOpenNSLTransmittedPkts128to255Octets, snmpOpenNSLTransmittedPkts1519to2047Octets, snmpOpenNSLTransmittedPkts2048to4095Octets, snmpOpenNSLTransmittedPkts256to511Octets, snmpOpenNSLTransmittedPkts4095to9216Octets, snmpOpenNSLTransmittedPkts512to1023Octets, snmpOpenNSLTransmittedPkts64Octets, and snmpOpenNSLTransmittedPkts65to127Octets.
Variable Documentation
char example_usage[]
Initial value:
=
"Syntax: example_stat                                                  \n\r"
"                                                                      \n\r"
"Paramaters: None                                                      \n\r"
"                                                                      \n\r"
"Example: The following command is used to see the statistics of a port\n\r"
"         example_stat                                                 \n\r"
"                                                                      \n\r"
"Usage Guidelines: This program request the user to enter the port     \n\r"
"                  number interactively                                \n\r"
Definition at line 43 of file example_stat.c.