OpenNSL API Guide and Reference Manual: Resource Management
Resource Management
Data Structures
struct opennsl_rm_profile_s
RM profile structure.
Files
file rmapi.h
Macros
#define RM_MAX_CLIENT_ID (RM_MAX_CLIENTS - 1)
#define RM_MAX_CLIENTS 3
#define RM_MAX_UNITS 1
#define RM_MIN_CLIENT_ID 1
Typedefs
typedef struct opennsl_rm_profile_s opennsl_rm_profile_t
RM profile structure.
typedef enum opennsl_rm_retval_e opennsl_rm_retval_t
opennsl_rm_retval_t
Enumerations
enum opennsl_rm_retval_e {
OPENNSL_RM_E_NONE = 0,
OPENNSL_RM_E_INVALID_INPUT = -1,
OPENNSL_RM_E_INVALID_CLNT_ID = -2,
OPENNSL_RM_E_INVALID_L2_ENTRY_LIMIT = -3,
OPENNSL_RM_E_MEMALLOC_FAIL = -4,
OPENNSL_RM_E_CLNT_LIMIT_EXCEEDED = -5,
OPENNSL_RM_E_PHYPORT_CONFLICT = -6,
OPENNSL_RM_E_VLAN_CONFLICT = -7,
OPENNSL_RM_E_UNREGISTERED_CLNT_ID = -8,
OPENNSL_RM_E_L2TABLE_LIMIT_EXCEEDED = -9,
OPENNSL_RM_E_INTERNAL = -10,
OPENNSL_RM_E_LIMIT = -11
}
opennsl_rm_retval_t
Functions
int opennsl_rm_deregister (uint16 client_id) LIB_DLL_EXPORTED
Used to de-register with Resource Manager.
char * opennsl_rm_errmsg (int err) LIB_DLL_EXPORTED
Return Resource Manager error string based on the error code.
int opennsl_rm_profile_get (uint16 client_id, opennsl_rm_profile_t *profile) LIB_DLL_EXPORTED
Used to get the resource profile registered with Resource Manager.
int opennsl_rm_profile_ports_update (uint16 client_id, int unit, opennsl_pbmp_t ports) LIB_DLL_EXPORTED
Used to update the registered ports with the Resource Manager for a given client.
int opennsl_rm_profile_vlans_update (uint16 client_id, opennsl_vlan_vector_t vlans) LIB_DLL_EXPORTED
Used to update the registered vlans with the Resource Manager for a given client.
int opennsl_rm_register (opennsl_rm_profile_t *profile, uint16 *client_id) LIB_DLL_EXPORTED
Used to register with Resource Manager.
Detailed Description
Macro Definition Documentation
#define RM_MAX_CLIENT_ID (RM_MAX_CLIENTS - 1)
Definition at line 33 of file rmapi.h.
#define RM_MAX_CLIENTS 3
Definition at line 30 of file rmapi.h.
#define RM_MAX_UNITS 1
Definition at line 29 of file rmapi.h.
Referenced by example_rm_show_profile().
#define RM_MIN_CLIENT_ID 1
Definition at line 32 of file rmapi.h.
Typedef Documentation
typedef struct opennsl_rm_profile_s opennsl_rm_profile_t
RM profile structure.
typedef enum opennsl_rm_retval_e opennsl_rm_retval_t
opennsl_rm_retval_t
Enumeration Type Documentation
enum opennsl_rm_retval_e
opennsl_rm_retval_t
Enumerator:
OPENNSL_RM_E_NONE
No Error.
OPENNSL_RM_E_INVALID_INPUT
Invalid Input.
OPENNSL_RM_E_INVALID_CLNT_ID
Invalid Client ID.
OPENNSL_RM_E_INVALID_L2_ENTRY_LIMIT
Invalid L2_ENTRY_CNT value.
OPENNSL_RM_E_MEMALLOC_FAIL
Memory allocation failed.
OPENNSL_RM_E_CLNT_LIMIT_EXCEEDED
Maximum clients reached.
OPENNSL_RM_E_PHYPORT_CONFLICT
Requested ports already used.
OPENNSL_RM_E_VLAN_CONFLICT
Requested VLANs already used.
OPENNSL_RM_E_UNREGISTERED_CLNT_ID
Unregistered client ID.
OPENNSL_RM_E_L2TABLE_LIMIT_EXCEEDED
L2_Table limit exceeded.
OPENNSL_RM_E_INTERNAL
Internal error.
OPENNSL_RM_E_LIMIT
Must be last.
Definition at line 36 of file rmapi.h.
Function Documentation
int opennsl_rm_deregister (uint16 client_id)
Used to de-register with Resource Manager.
Description
This API de-registers already registered client with the Resource Management(RM) module in OpenNSL.
Parameters
client_id [IN] Client ID obtained on successful registration
Return values
OPENNSL_RM_E_XXX
char* opennsl_rm_errmsg (int err)
Return Resource Manager error string based on the error code.
Description
Return Resource Manager error string based on the error code
Parameters
rv [IN] error code
Return values
Resource manager error string
int opennsl_rm_profile_get (uint16 client_id, opennsl_rm_profile_t * profile)
Used to get the resource profile registered with Resource Manager.
Description
Given a valid client ID, this API returns the profile structure registered with the Resource Manager(RM) in OpenNSL.
Parameters
client_id [IN] Client ID obtained on successful registration
profile [OUT] Pointer to the structure filled with resource requirements.
Return values
OPENNSL_RM_E_XXX
Referenced by main().
int opennsl_rm_profile_ports_update (uint16 client_id, int unit, opennsl_pbmp_t ports)
Used to update the registered ports with the Resource Manager for a given client.
Description
Each client which wants to use the resource manager(RM) functionality in OpenNSL, will register its requirements via a profile structure. If the client later wants to change its ports requirement, it can use this API to update the ports value of the profile.
Parameters
client_id [IN] client ID returned by RM on successful registration
unit [IN] unit ID for which the ports ownership is to be updated
ports [OUT] New bitmap of the requested ports
Return values
OPENNSL_RM_E_XXX
Referenced by main().
int opennsl_rm_profile_vlans_update (uint16 client_id, opennsl_vlan_vector_t vlans)
Used to update the registered vlans with the Resource Manager for a given client.
Description
Each client which wants to use the resource manager(RM) functionality in OpenNSL, will register its requirements via a profile structure. If the client later wants to change its vlans requirement, it can use this API to update the vlans value of the profile.
Parameters
client_id [IN] client ID returned by RM on successful registration
vlans [OUT] New bitmap of the requested vlans
Return values
OPENNSL_RM_E_XXX
Referenced by main().
int opennsl_rm_register (opennsl_rm_profile_t * profile, uint16 * client_id)
Used to register with Resource Manager.
Description
Each client which wants to use the resource manager(RM) functionality in OpenNSL, should register its requirements via a profile structure. This API validates the passed requirements along with the already registered clients and on successful registration returns a Client ID.
Parameters
profile [IN] Pointer to the structure filled with resource requirements.
client_id [OUT] Client ID assigned on successful registration
Return values
OPENNSL_RM_E_XXX