OpenNSL API Guide and Reference Manual: Virtual LAN Management
Virtual LAN Management
Data Structures
struct opennsl_vlan_data_s
Initialize a VLAN data information structure.
struct opennsl_vlan_protocol_packet_ctrl_s
Per VLAN Protocol Packet control.
Files
file vlan.h
file vlanX.h
Typedefs
typedef enum
opennsl_vlan_control_port_e opennsl_vlan_control_port_t
opennsl_vlan_control_port_t
typedef enum opennsl_vlan_control_e opennsl_vlan_control_t
opennsl_vlan_control_t
typedef struct opennsl_vlan_data_s opennsl_vlan_data_t
Initialize a VLAN data information structure.
typedef struct
opennsl_vlan_protocol_packet_ctrl_s opennsl_vlan_protocol_packet_ctrl_t
Per VLAN Protocol Packet control.
Enumerations
enum opennsl_vlan_control_e {
opennslVlanDropUnknown = 0,
opennslVlanShared = 3,
opennslVlanSharedID = 4,
opennslVlanTranslate = 5,
opennslVlanIgnorePktTag = 6,
opennslVlanMemberMismatchToCpu = 21
}
opennsl_vlan_control_t
enum opennsl_vlan_control_port_e {
opennslVlanTranslateIngressEnable = 2,
opennslVlanTranslateIngressMissDrop = 4,
opennslVlanTranslateEgressEnable = 5,
opennslVlanTranslateEgressMissDrop = 6
}
opennsl_vlan_control_port_t
Functions
int opennsl_vlan_control_port_set (int unit, int port, opennsl_vlan_control_port_t type, int arg) LIB_DLL_EXPORTED
Set/get miscellaneous port-specific VLAN options.
int opennsl_vlan_control_set (int unit, opennsl_vlan_control_t type, int arg) LIB_DLL_EXPORTED
Set/get miscellaneous VLAN-specific chip options.
int opennsl_vlan_create (int unit, opennsl_vlan_t vid) LIB_DLL_EXPORTED
Allocate and configure a VLAN on the OPENNSL device.
int opennsl_vlan_default_get (int unit, opennsl_vlan_t *vid_ptr) LIB_DLL_EXPORTED
Get the default VLAN ID.
int opennsl_vlan_default_set (int unit, opennsl_vlan_t vid) LIB_DLL_EXPORTED
Set the default VLAN ID.
int opennsl_vlan_destroy (int unit, opennsl_vlan_t vid) LIB_DLL_EXPORTED
Deallocate VLAN from the OPENNSL device.
int opennsl_vlan_destroy_all (int unit) LIB_DLL_EXPORTED
Destroy all VLANs except the default VLAN.
int opennsl_vlan_gport_add (int unit, opennsl_vlan_t vlan, opennsl_gport_t port, int flags) LIB_DLL_EXPORTED
Add a virtual or physical port to the specified VLAN.
int opennsl_vlan_gport_delete (int unit, opennsl_vlan_t vlan, opennsl_gport_t port) LIB_DLL_EXPORTED
Remove a virtual or physical port from the specified VLAN.
int opennsl_vlan_gport_delete_all (int unit, opennsl_vlan_t vlan) LIB_DLL_EXPORTED
Removes all virtual and physical port from the specified VLAN.
int opennsl_vlan_gport_get (int unit, opennsl_vlan_t vlan, opennsl_gport_t port, int *flags) LIB_DLL_EXPORTED
Get a virtual or physical port from the specified VLAN.
int opennsl_vlan_list (int unit, opennsl_vlan_data_t **listp, int *countp) LIB_DLL_EXPORTED
Returns an array of defined VLANs and their port bitmaps.
int opennsl_vlan_list_destroy (int unit, opennsl_vlan_data_t *list, int count) LIB_DLL_EXPORTED
Destroy a list returned by opennsl_vlan_list.
int opennsl_vlan_port_add (int unit, opennsl_vlan_t vid, opennsl_pbmp_t pbmp, opennsl_pbmp_t ubmp) LIB_DLL_EXPORTED
Add ports to the specified VLAN.
int opennsl_vlan_port_remove (int unit, opennsl_vlan_t vid, opennsl_pbmp_t pbmp) LIB_DLL_EXPORTED
Remove ports from a specified VLAN.
Detailed Description
Typedef Documentation
typedef enum opennsl_vlan_control_port_e opennsl_vlan_control_port_t
opennsl_vlan_control_port_t
typedef enum opennsl_vlan_control_e opennsl_vlan_control_t
opennsl_vlan_control_t
typedef struct opennsl_vlan_data_s opennsl_vlan_data_t
Initialize a VLAN data information structure.
typedef struct opennsl_vlan_protocol_packet_ctrl_s opennsl_vlan_protocol_packet_ctrl_t
Per VLAN Protocol Packet control.
A protocol packet type is copied to CPU if the packet control value is set to VLAN_PROTO_PKT_TOCPU_ENABLE. Additionally the control can be set to one of VLAN_PROTO_PKT_FORWARD_ENABLE, VLAN_PROTO_PKT_DROP_ENABLE, or VLAN_PROTO_PKT_FLOOD_ENABLE to forward, drop or flood in VLAN respectively.
Enumeration Type Documentation
enum opennsl_vlan_control_e
opennsl_vlan_control_t
Enumerator:
opennslVlanDropUnknown
Drop unknown/FFF VLAN pkts or send to CPU.
opennslVlanShared
Shared vs.
Independent VLAN Learning.
opennslVlanSharedID
Shared Learning VLAN ID.
opennslVlanTranslate
Chip is in VLAN translate mode.
opennslVlanIgnorePktTag
Ignore Packet VLAN tag.
Treat packet as untagged.
opennslVlanMemberMismatchToCpu
Packets' incoming port is not the member of the VLAN are sent to CPU when set to 1.
Definition at line 318 of file vlan.h.
enum opennsl_vlan_control_port_e
opennsl_vlan_control_port_t
Enumerator:
opennslVlanTranslateIngressEnable
opennslVlanTranslateIngressMissDrop
opennslVlanTranslateEgressEnable
opennslVlanTranslateEgressMissDrop
Definition at line 356 of file vlan.h.
Function Documentation
int opennsl_vlan_control_port_set (int unit, int port, opennsl_vlan_control_port_t type, int arg)
Set/get miscellaneous port-specific VLAN options.
Description
Sets/gets miscellaneous port-specific VLAN options. The options are from the VLAN Control Port selection =vlan_ctrl_port . Notes: (1) When setting egress vlan translation lookup key for virtual ports, control type should be one of {opennslVlanPortTranslateEgressKey or opennslVlanPortTranslateEgressKeyFirst}. Also, the argument specifying key type in case of virtual ports should be one of {opennslVlanTranslateEgressKeyVpn, opennslVlanTranslateEgressKeyVpnGport, opennslVlanTranslateEgressKeyVpnGportGroup}. (2) When setting the key for explicit second vlan translation lookup using opennslVlanPortTranslateEgressKeySecond, the argument specifying key type should be one of {opennslVlanTranslateEgressKeyPortGroupDouble, opennslVlanTranslateEgressKeyPortDouble}.
Parameters
unit [IN] Unit number.
port [IN] Device or logical port number
type [IN] A value from the opennsl_vlan_control_port_t enumerated list
arg [IN] (for _set) A parameter whose meaning is dependent on 'type'
Return values
OPENNSL_E_UNAVAIL Feature not supported.
OPENNSL_E_XXX
int opennsl_vlan_control_set (int unit, opennsl_vlan_control_t type, int arg)
Set/get miscellaneous VLAN-specific chip options.
Description
Sets/gets miscellaneous VLAN-specific chip options. The options are from the VLAN Control selection =vlan_ctrl.
Parameters
unit [IN] Unit number.
type [IN] A value from the opennsl_vlan_control_t enumerated list
arg [IN] (for _set) A parameter whose meaning is dependent on 'type'
Return values
OPENNSL_E_UNAVAIL Feature not supported.
OPENNSL_E_XXX
int opennsl_vlan_create (int unit, opennsl_vlan_t vid)
Allocate and configure a VLAN on the OPENNSL device.
Description
Create a new VLAN with the given ID. This routine will satisfy requests until the number of VLANs supported in the underlying hardware is reached. The VLAN is placed in the default STG and can be reassigned later. To deallocate the VLAN, opennsl_vlan_destroy must be used, not opennsl_vlan_init, since opennsl_vlan_init does not remove the VLAN from its STG. See =switch for default multicast flood mode configuration.
Parameters
unit [IN] Unit number.
vid [IN] VLAN ID
Return values
OPENNSL_E_NONE Success or when the default VLAN is created, even if it already exists.
OPENNSL_E_XXX
OPENNSL_E_EXISTS VLAN ID already in use.
Referenced by example_create_l3_intf(), example_stg_create(), example_vlan_port_add(), and vlan_create_add_port().
int opennsl_vlan_default_get (int unit, opennsl_vlan_t * vid_ptr)
Get the default VLAN ID.
Description
Retrieve the current default VLAN ID.
Parameters
unit [IN] Unit number.
vid_ptr [OUT] Current default VLAN ID
Return values
OPENNSL_E_NONE Success.
int opennsl_vlan_default_set (int unit, opennsl_vlan_t vid)
Set the default VLAN ID.
Description
Change the default VLAN to the specified VLAN ID. The new default VLAN must already exist. .
Parameters
unit [IN] Unit number.
vid [IN] New default VLAN ID
Return values
OPENNSL_E_XXX
int opennsl_vlan_destroy (int unit, opennsl_vlan_t vid)
Deallocate VLAN from the OPENNSL device.
Description
Remove references to previously created VLAN. Ports whose port-based VLAN is the destroyed VID are given the default VID.
Parameters
unit [IN] Unit number.
vid [IN] VLAN ID
Return values
OPENNSL_E_BADID Cannot remove default VLAN
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX
Referenced by revert_stg().
int opennsl_vlan_destroy_all (int unit)
Destroy all VLANs except the default VLAN.
Description
Destroy all VLANs except the default VLAN.
Parameters
unit [IN] Unit number.
Return values
OPENNSL_E_XXX
int opennsl_vlan_gport_add (int unit, opennsl_vlan_t vlan, opennsl_gport_t port, int flags)
Add a virtual or physical port to the specified VLAN.
Description
Adds the given port to the VLAN. For network switch and network switch, the port can be either a WLAN virtual port or a regular physical port. For network switch, the port can be a layer 2 logical port or a regular physical port. WLAN virtual ports or layer 2 logical ports that are members of a VLAN will receive broadcast, multicast and unknown unicast packets that are flooded to the VLAN. For applications that require different recipients for broadcast, unknown multicast and unknown unicast, the different multicast groups can be set using the =opennsl_vlan_control_vlan_set API. Virtual Port(VP) can be added to the vlan through this API to obtain the vlan membership. Due to the large amount of virtual port number, unlike physical port, switch hardware can not uses a port bitmap in the vlan table entry to represent the vlan membership. Instead the hardware uses two different methods: VP group and hash table to provide VP vlan membership. The hash table method is only available on opennsl56850 and later switch devices. The VP group referring as indirect vlan membership method is to associate a group of virtual port with a VP group and then the VP group establishes the membership with the vlan. The hardware uses the VLAN_MEMBERSHIP_PROFILE field in the SOURCE_VP table to associate a virtual port with the VP group, and use the VP_GROUP_BITMAP field in the vlan table to establish the vlan membership with the VP group. This method works well when a group of VPs belong to the same number of vlans such as in the following case:.
Parameters
unit [IN] Unit number.
vlan [IN] VLAN ID
port [IN] Virtual or physical port to be added to the VLAN
flags [IN] Control flags. See =OPENNSL_VLAN_PORT_t
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX
Referenced by example_create_l3_intf().
int opennsl_vlan_gport_delete (int unit, opennsl_vlan_t vlan, opennsl_gport_t port)
Remove a virtual or physical port from the specified VLAN.
Description
Removes the given port to the VLAN. For network switch and network switch, the port can be either a WLAN virtual port or a regular physical port. For network switch, the port can be a layer 2 logical port or a regular physical port.
Parameters
unit [IN] Unit number.
vlan [IN] VLAN ID
port [IN] Virtual or physical port to be removed from the VLAN
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX
int opennsl_vlan_gport_delete_all (int unit, opennsl_vlan_t vlan)
Removes all virtual and physical port from the specified VLAN.
Description
Removes all virtual and physical ports from the specified VLAN.
Parameters
unit [IN] Unit number.
vlan [IN] VLAN ID
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX
int opennsl_vlan_gport_get (int unit, opennsl_vlan_t vlan, opennsl_gport_t port, int * flags)
Get a virtual or physical port from the specified VLAN.
Description
Checks whether the given port is a member of the VLAN. For network switch and network switch, the port can be either a WLAN virtual port or a regular physical port. For network switch, the port can be a layer 2 logical port or a regular physical port.
Parameters
unit [IN] Unit number.
vlan [IN] VLAN ID
port [IN] Virtual or physical port to get VLAN information
flags [OUT] Control flags. See =OPENNSL_VLAN_PORT_t
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use or port is not a member
OPENNSL_E_XXX
int opennsl_vlan_list (int unit, opennsl_vlan_data_t ** listp, int * countp)
Returns an array of defined VLANs and their port bitmaps.
If by pbmp, then only VLANs which contain at least one of the specified ports are listed.
Description
Returns an array of defined VLANs and their port bitmaps. If by pbmp, only VLANs which contain at least one of the specified ports are listed. The array is allocated by this routine and the pointer to the list is returned in *listp. This array should be destroyed by opennsl_vlan_list_destroy when it is no longer needed. See =vlan_data .
Parameters
unit [IN] Unit number.
listp [OUT] Place where pointer to return array will be stored, which will be NULL if there are zero VLANs defined.
countp [OUT] Place where number of entries in array will be stored, which will be 0 if there are zero VLANs defined.
Return values
OPENNSL_E_MEMORY Out of system memory.
OPENNSL_E_XXX
int opennsl_vlan_list_destroy (int unit, opennsl_vlan_data_t * list, int count)
Destroy a list returned by opennsl_vlan_list.
Description
Deallocate the array created by opennsl_vlan_list or opennsl_vlan_list_by_pbmp. Also works for the zero-VLAN case (NULL list).
Parameters
unit [IN] Unit number.
list [IN] List returned by opennsl_vlan_list
count [IN] Count returned by opennsl_vlan_list
Return values
OPENNSL_E_NONE Success.
int opennsl_vlan_port_add (int unit, opennsl_vlan_t vid, opennsl_pbmp_t pbmp, opennsl_pbmp_t ubmp)
Add ports to the specified VLAN.
Description
Adds the selected ports to the VLAN. The port bitmap specifies ALL ports to be added to the VLAN. The untagged bitmap specifies the subset of these ports that are untagged. If the port is already a member of the VLAN then the tagged attribute gets updated. Packets sent from the untagged ports will not contain the 802.1Q tag header. .
Parameters
unit [IN] Unit number.
vid [IN] VLAN ID
pbmp [IN] Port bitmap for members of VLAN
ubmp [IN] Port bitmap for untagged members of VLAN
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX
Referenced by example_stg_create(), example_switch_default_vlan_config(), example_vlan_port_add(), main(), and vlan_create_add_port().
int opennsl_vlan_port_remove (int unit, opennsl_vlan_t vid, opennsl_pbmp_t pbmp)
Remove ports from a specified VLAN.
Description
Removes the specified ports from the given VLAN. If some or all of the requested ports are not already members of the VLAN, the routine returns OPENNSL_E_NOT_FOUND.
Parameters
unit [IN] Unit number.
vid [IN] VLAN ID
pbmp [IN] Port bitmap for members of VLAN
Return values
OPENNSL_E_NOT_FOUND VLAN ID not in use
OPENNSL_E_XXX