OpenNSL API Guide and Reference Manual: Statistics
Statistics
Data Structures
struct opennsl_stat_group_mode_attr_selector_s
Stat Flex Group Attribute Selector.
struct opennsl_stat_value_s
Counter Statistics Values.
Files
file stat.h
file statX.h
Macros
#define OPENNSL_STAT_GROUP_MODE_INGRESS 0x00000001
Stat Group Mode Ingress.
Typedefs
typedef enum
opennsl_stat_group_mode_attr_pkt_type_e opennsl_stat_group_mode_attr_pkt_type_t
Packet type related flex attributes values.
typedef struct
opennsl_stat_group_mode_attr_selector_s opennsl_stat_group_mode_attr_selector_t
Stat Flex Group Attribute Selector.
typedef enum
opennsl_stat_group_mode_attr_e opennsl_stat_group_mode_attr_t
Stat Group Mode Attribute Selectors.
typedef enum
opennsl_stat_group_mode_e opennsl_stat_group_mode_t
Statistics Group Modes.
typedef enum opennsl_stat_object_e opennsl_stat_object_t
Ingress and Egress Statistics Accounting Objects.
typedef enum opennsl_stat_val_e opennsl_stat_val_t
Statistics counters.
typedef struct opennsl_stat_value_s opennsl_stat_value_t
Counter Statistics Values.
Enumerations
enum opennsl_stat_group_mode_attr_e {
opennslStatGroupModeAttrColor = 1,
opennslStatGroupModeAttrFieldIngressColor = 2,
opennslStatGroupModeAttrIntPri = 3,
opennslStatGroupModeAttrVlan = 4,
opennslStatGroupModeAttrOuterPri = 5,
opennslStatGroupModeAttrInnerPri = 6,
opennslStatGroupModeAttrPort = 7,
opennslStatGroupModeAttrTosDscp = 8,
opennslStatGroupModeAttrPktType = 10,
opennslStatGroupModeAttrIngNetworkGroup = 11,
opennslStatGroupModeAttrDrop = 13,
opennslStatGroupModeAttrPacketTypeIp = 14
}
Stat Group Mode Attribute Selectors.
enum opennsl_stat_group_mode_attr_pkt_type_e {
opennslStatGroupModeAttrPktTypeKnownL3UC = 14,
opennslStatGroupModeAttrPktTypeUnknownL3UC = 15,
opennslStatGroupModeAttrPktTypeKnownIPMC = 16,
opennslStatGroupModeAttrPktTypeUnknownIPMC = 17
}
Packet type related flex attributes values.
enum opennsl_stat_group_mode_e {
opennslStatGroupModeSingle = 0,
opennslStatGroupModeTrafficType = 1
}
Statistics Group Modes.
enum opennsl_stat_object_e {
opennslStatObjectIngL3Intf = 4,
opennslStatObjectEgrL3Intf = 13
}
Ingress and Egress Statistics Accounting Objects.
enum opennsl_stat_val_e {
opennsl_spl_snmpIfInOctets = 0,
opennsl_spl_snmpIfInUcastPkts = 1,
opennsl_spl_snmpIfInNUcastPkts = 2,
opennsl_spl_snmpIfInDiscards = 3,
opennsl_spl_snmpIfInErrors = 4,
opennsl_spl_snmpIfInUnknownProtos = 5,
opennsl_spl_snmpIfOutOctets = 6,
opennsl_spl_snmpIfOutUcastPkts = 7,
opennsl_spl_snmpIfOutNUcastPkts = 8,
opennsl_spl_snmpIfOutDiscards = 9,
opennsl_spl_snmpIfOutErrors = 10,
opennsl_spl_snmpIfOutQLen = 11,
opennsl_spl_snmpIpInReceives = 12,
opennsl_spl_snmpIpInHdrErrors = 13,
opennsl_spl_snmpIpForwDatagrams = 14,
opennsl_spl_snmpIpInDiscards = 15,
opennsl_spl_snmpDot1dBasePortDelayExceededDiscards = 16,
opennsl_spl_snmpDot1dBasePortMtuExceededDiscards = 17,
opennsl_spl_snmpDot1dTpPortInFrames = 18,
opennsl_spl_snmpDot1dTpPortOutFrames = 19,
opennsl_spl_snmpDot1dPortInDiscards = 20,
opennsl_spl_snmpEtherStatsDropEvents = 21,
opennsl_spl_snmpEtherStatsMulticastPkts = 22,
opennsl_spl_snmpEtherStatsBroadcastPkts = 23,
opennsl_spl_snmpEtherStatsUndersizePkts = 24,
opennsl_spl_snmpEtherStatsFragments = 25,
opennsl_spl_snmpEtherStatsPkts64Octets = 26,
opennsl_spl_snmpEtherStatsPkts65to127Octets = 27,
opennsl_spl_snmpEtherStatsPkts128to255Octets = 28,
opennsl_spl_snmpEtherStatsPkts256to511Octets = 29,
opennsl_spl_snmpEtherStatsPkts512to1023Octets = 30,
opennsl_spl_snmpEtherStatsPkts1024to1518Octets = 31,
opennsl_spl_snmpEtherStatsOversizePkts = 32,
opennsl_spl_snmpEtherRxOversizePkts = 33,
opennsl_spl_snmpEtherTxOversizePkts = 34,
opennsl_spl_snmpEtherStatsJabbers = 35,
opennsl_spl_snmpEtherStatsOctets = 36,
opennsl_spl_snmpEtherStatsPkts = 37,
opennsl_spl_snmpEtherStatsCollisions = 38,
opennsl_spl_snmpEtherStatsCRCAlignErrors = 39,
opennsl_spl_snmpEtherStatsTXNoErrors = 40,
opennsl_spl_snmpEtherStatsRXNoErrors = 41,
opennsl_spl_snmpDot3StatsAlignmentErrors = 42,
opennsl_spl_snmpDot3StatsFCSErrors = 43,
opennsl_spl_snmpDot3StatsSingleCollisionFrames = 44,
opennsl_spl_snmpDot3StatsMultipleCollisionFrames = 45,
opennsl_spl_snmpDot3StatsSQETTestErrors = 46,
opennsl_spl_snmpDot3StatsDeferredTransmissions = 47,
opennsl_spl_snmpDot3StatsLateCollisions = 48,
opennsl_spl_snmpDot3StatsExcessiveCollisions = 49,
opennsl_spl_snmpDot3StatsInternalMacTransmitErrors = 50,
opennsl_spl_snmpDot3StatsCarrierSenseErrors = 51,
opennsl_spl_snmpDot3StatsFrameTooLongs = 52,
opennsl_spl_snmpDot3StatsInternalMacReceiveErrors = 53,
opennsl_spl_snmpDot3StatsSymbolErrors = 54,
opennsl_spl_snmpDot3ControlInUnknownOpcodes = 55,
opennsl_spl_snmpDot3InPauseFrames = 56,
opennsl_spl_snmpDot3OutPauseFrames = 57,
opennsl_spl_snmpIfHCInOctets = 58,
opennsl_spl_snmpIfHCInUcastPkts = 59,
opennsl_spl_snmpIfHCInMulticastPkts = 60,
opennsl_spl_snmpIfHCInBroadcastPkts = 61,
opennsl_spl_snmpIfHCOutOctets = 62,
opennsl_spl_snmpIfHCOutUcastPkts = 63,
opennsl_spl_snmpIfHCOutMulticastPkts = 64,
opennsl_spl_snmpIfHCOutBroadcastPckts = 65,
opennsl_spl_snmpIpv6IfStatsInReceives = 66,
opennsl_spl_snmpIpv6IfStatsInHdrErrors = 67,
opennsl_spl_snmpIpv6IfStatsInAddrErrors = 68,
opennsl_spl_snmpIpv6IfStatsInDiscards = 69,
opennsl_spl_snmpIpv6IfStatsOutForwDatagrams = 70,
opennsl_spl_snmpIpv6IfStatsOutDiscards = 71,
opennsl_spl_snmpIpv6IfStatsInMcastPkts = 72,
opennsl_spl_snmpIpv6IfStatsOutMcastPkts = 73,
opennsl_spl_snmpIfInBroadcastPkts = 74,
opennsl_spl_snmpIfInMulticastPkts = 75,
opennsl_spl_snmpIfOutBroadcastPkts = 76,
opennsl_spl_snmpIfOutMulticastPkts = 77,
opennsl_spl_snmpIeee8021PfcRequests = 78,
opennsl_spl_snmpIeee8021PfcIndications = 79,
snmpOpenNSLReceivedUndersizePkts = 80,
snmpOpenNSLTransmittedUndersizePkts = 81,
snmpOpenNSLIPMCBridgedPckts = 82,
snmpOpenNSLIPMCRoutedPckts = 83,
snmpOpenNSLIPMCInDroppedPckts = 84,
snmpOpenNSLIPMCOutDroppedPckts = 85,
snmpOpenNSLEtherStatsPkts1519to1522Octets = 86,
snmpOpenNSLEtherStatsPkts1522to2047Octets = 87,
snmpOpenNSLEtherStatsPkts2048to4095Octets = 88,
snmpOpenNSLEtherStatsPkts4095to9216Octets = 89,
snmpOpenNSLReceivedPkts64Octets = 90,
snmpOpenNSLReceivedPkts65to127Octets = 91,
snmpOpenNSLReceivedPkts128to255Octets = 92,
snmpOpenNSLReceivedPkts256to511Octets = 93,
snmpOpenNSLReceivedPkts512to1023Octets = 94,
snmpOpenNSLReceivedPkts1024to1518Octets = 95,
snmpOpenNSLReceivedPkts1519to2047Octets = 96,
snmpOpenNSLReceivedPkts2048to4095Octets = 97,
snmpOpenNSLReceivedPkts4095to9216Octets = 98,
snmpOpenNSLTransmittedPkts64Octets = 99,
snmpOpenNSLTransmittedPkts65to127Octets = 100,
snmpOpenNSLTransmittedPkts128to255Octets = 101,
snmpOpenNSLTransmittedPkts256to511Octets = 102,
snmpOpenNSLTransmittedPkts512to1023Octets = 103,
snmpOpenNSLTransmittedPkts1024to1518Octets = 104,
snmpOpenNSLTransmittedPkts1519to2047Octets = 105,
snmpOpenNSLTransmittedPkts2048to4095Octets = 106,
snmpOpenNSLTransmittedPkts4095to9216Octets = 107,
snmpOpenNSLTxControlCells = 108,
snmpOpenNSLTxDataCells = 109,
snmpOpenNSLTxDataBytes = 110,
snmpOpenNSLRxCrcErrors = 111,
snmpOpenNSLRxFecCorrectable = 112,
snmpOpenNSLRxBecCrcErrors = 113,
snmpOpenNSLRxDisparityErrors = 114,
snmpOpenNSLRxControlCells = 115,
snmpOpenNSLRxDataCells = 116,
snmpOpenNSLRxDataBytes = 117,
snmpOpenNSLRxDroppedRetransmittedControl = 118,
snmpOpenNSLTxBecRetransmit = 119,
snmpOpenNSLRxBecRetransmit = 120,
snmpOpenNSLTxAsynFifoRate = 121,
snmpOpenNSLRxAsynFifoRate = 122,
snmpOpenNSLRxFecUncorrectable = 123,
snmpOpenNSLRxBecRxFault = 124,
snmpOpenNSLRxCodeErrors = 125,
snmpOpenNSLRxLlfcPrimary = 126,
snmpOpenNSLRxLlfcSecondary = 127,
snmpOpenNSLCustomReceive0 = 128,
snmpOpenNSLCustomReceive1 = 129,
snmpOpenNSLCustomReceive2 = 130,
snmpOpenNSLCustomReceive3 = 131,
snmpOpenNSLCustomReceive4 = 132,
snmpOpenNSLCustomReceive5 = 133,
snmpOpenNSLCustomReceive6 = 134,
snmpOpenNSLCustomReceive7 = 135,
snmpOpenNSLCustomReceive8 = 136,
snmpOpenNSLCustomTransmit0 = 137,
snmpOpenNSLCustomTransmit1 = 138,
snmpOpenNSLCustomTransmit2 = 139,
snmpOpenNSLCustomTransmit3 = 140,
snmpOpenNSLCustomTransmit4 = 141,
snmpOpenNSLCustomTransmit5 = 142,
snmpOpenNSLCustomTransmit6 = 143,
snmpOpenNSLCustomTransmit7 = 144,
snmpOpenNSLCustomTransmit8 = 145,
snmpOpenNSLCustomTransmit9 = 146,
snmpOpenNSLCustomTransmit10 = 147,
snmpOpenNSLCustomTransmit11 = 148,
snmpOpenNSLCustomTransmit12 = 149,
snmpOpenNSLCustomTransmit13 = 150,
snmpOpenNSLCustomTransmit14 = 151,
opennsl_spl_snmpDot3StatsInRangeLengthError = 152,
opennsl_spl_snmpDot3OmpEmulationCRC8Errors = 153,
opennsl_spl_snmpDot3MpcpRxGate = 154,
opennsl_spl_snmpDot3MpcpRxRegister = 155,
opennsl_spl_snmpDot3MpcpTxRegRequest = 156,
opennsl_spl_snmpDot3MpcpTxRegAck = 157,
opennsl_spl_snmpDot3MpcpTxReport = 158,
opennsl_spl_snmpDot3EponFecCorrectedBlocks = 159,
opennsl_spl_snmpDot3EponFecUncorrectableBlocks = 160,
snmpOpenNSLPonInDroppedOctets = 161,
snmpOpenNSLPonOutDroppedOctets = 162,
snmpOpenNSLPonInDelayedOctets = 163,
snmpOpenNSLPonOutDelayedOctets = 164,
snmpOpenNSLPonInDelayedHundredUs = 165,
snmpOpenNSLPonOutDelayedHundredUs = 166,
snmpOpenNSLPonInFrameErrors = 167,
snmpOpenNSLPonInOamFrames = 168,
snmpOpenNSLPonOutOamFrames = 169,
snmpOpenNSLPonOutUnusedOctets = 170,
snmpOpenNSLEtherStatsPkts9217to16383Octets = 171,
snmpOpenNSLReceivedPkts9217to16383Octets = 172,
snmpOpenNSLTransmittedPkts9217to16383Octets = 173,
snmpOpenNSLRxVlanTagFrame = 174,
snmpOpenNSLRxDoubleVlanTagFrame = 175,
snmpOpenNSLTxVlanTagFrame = 176,
snmpOpenNSLTxDoubleVlanTagFrame = 177,
snmpOpenNSLRxPFCControlFrame = 178,
snmpOpenNSLTxPFCControlFrame = 179,
snmpOpenNSLRxPFCFrameXonPriority0 = 180,
snmpOpenNSLRxPFCFrameXonPriority1 = 181,
snmpOpenNSLRxPFCFrameXonPriority2 = 182,
snmpOpenNSLRxPFCFrameXonPriority3 = 183,
snmpOpenNSLRxPFCFrameXonPriority4 = 184,
snmpOpenNSLRxPFCFrameXonPriority5 = 185,
snmpOpenNSLRxPFCFrameXonPriority6 = 186,
snmpOpenNSLRxPFCFrameXonPriority7 = 187,
snmpOpenNSLRxPFCFramePriority0 = 188,
snmpOpenNSLRxPFCFramePriority1 = 189,
snmpOpenNSLRxPFCFramePriority2 = 190,
snmpOpenNSLRxPFCFramePriority3 = 191,
snmpOpenNSLRxPFCFramePriority4 = 192,
snmpOpenNSLRxPFCFramePriority5 = 193,
snmpOpenNSLRxPFCFramePriority6 = 194,
snmpOpenNSLRxPFCFramePriority7 = 195,
snmpOpenNSLTxPFCFramePriority0 = 196,
snmpOpenNSLTxPFCFramePriority1 = 197,
snmpOpenNSLTxPFCFramePriority2 = 198,
snmpOpenNSLTxPFCFramePriority3 = 199,
snmpOpenNSLTxPFCFramePriority4 = 200,
snmpOpenNSLTxPFCFramePriority5 = 201,
snmpOpenNSLTxPFCFramePriority6 = 202,
snmpOpenNSLTxPFCFramePriority7 = 203,
opennsl_spl_snmpFcmPortClass3RxFrames = 204,
opennsl_spl_snmpFcmPortClass3TxFrames = 205,
opennsl_spl_snmpFcmPortClass3Discards = 206,
opennsl_spl_snmpFcmPortClass2RxFrames = 207,
opennsl_spl_snmpFcmPortClass2TxFrames = 208,
opennsl_spl_snmpFcmPortClass2Discards = 209,
opennsl_spl_snmpFcmPortInvalidCRCs = 210,
opennsl_spl_snmpFcmPortDelimiterErrors = 211,
snmpOpenNSLSampleIngressPkts = 212,
snmpOpenNSLSampleIngressSnapshotPkts = 213,
snmpOpenNSLSampleIngressSampledPkts = 214,
snmpOpenNSLSampleFlexPkts = 215,
snmpOpenNSLSampleFlexSnapshotPkts = 216,
snmpOpenNSLSampleFlexSampledPkts = 217,
snmpOpenNSLEgressProtectionDataDrop = 218,
snmpOpenNSLTxE2ECCControlFrames = 219,
snmpOpenNSLE2EHOLDropPkts = 220,
opennsl_spl_snmpEtherStatsTxCRCAlignErrors = 221,
opennsl_spl_snmpEtherStatsTxJabbers = 222,
opennsl_spl_snmpValCount = 223
}
Statistics counters.
Functions
int opennsl_stat_clear (int unit, opennsl_port_t port) LIB_DLL_EXPORTED
Clear the port-based statistics for the indicated device port.
int opennsl_stat_clear_single (int unit, opennsl_port_t port, opennsl_stat_val_t type) LIB_DLL_EXPORTED
Clear specific statistics for a port from the device.
int opennsl_stat_custom_group_create (int unit, uint32 mode_id, opennsl_stat_object_t object, uint32 *stat_counter_id, uint32 *num_entries) LIB_DLL_EXPORTED
Associate an accounting object to customized group mode.
int opennsl_stat_get (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint64 *value) LIB_DLL_EXPORTED
Get the specified statistics from the device.
int opennsl_stat_get32 (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint32 *value) LIB_DLL_EXPORTED
Get the specified statistics from the device.
int opennsl_stat_group_create (int unit, opennsl_stat_object_t object, opennsl_stat_group_mode_t group_mode, uint32 *stat_counter_id, uint32 *num_entries) LIB_DLL_EXPORTED
Create Counter Entries group for given accounting object.
int opennsl_stat_group_destroy (int unit, uint32 stat_counter_id) LIB_DLL_EXPORTED
Destroy counter Entries group.
void opennsl_stat_group_mode_attr_selector_t_init (opennsl_stat_group_mode_attr_selector_t *attr_selector) LIB_DLL_EXPORTED
Initialize an attribute selector of Stat Flex Group Mode.
int opennsl_stat_group_mode_id_create (int unit, uint32 flags, uint32 total_counters, uint32 num_selectors, opennsl_stat_group_mode_attr_selector_t *attr_selectors, uint32 *mode_id) LIB_DLL_EXPORTED
Create Customized Stat Group mode for given Counter Attributes In network switch, OAM LM is supported through Flex Counters, When OPENNSL_STAT_GROUP_MODE_CAPABILITY_OAM flag is passed along with OPENNSL_STAT_GROUP_MODE_INGRESS or OPENNSL_STAT_GROUP_MODE_EGRESS, it instructs the API to create a stat group suitable for OAM.
int opennsl_stat_group_mode_id_destroy (int unit, uint32 mode_id) LIB_DLL_EXPORTED
Destroys Customized Group mode.
int opennsl_stat_init (int unit) LIB_DLL_EXPORTED
Initialize the OPENNSL statistics module.
int opennsl_stat_multi_get (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t *stat_arr, uint64 *value_arr) LIB_DLL_EXPORTED
Get the specified statistics from the device.
int opennsl_stat_multi_get32 (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t *stat_arr, uint32 *value_arr) LIB_DLL_EXPORTED
Get the specified statistics from the device.
int opennsl_stat_sync (int unit) LIB_DLL_EXPORTED
Synchronize software counters with hardware.
int opennsl_stat_sync_get32 (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint32 *value) LIB_DLL_EXPORTED
Force an immediate counter update and get statistics for a specified device.
int opennsl_stat_sync_multi_get32 (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t *stat_arr, uint32 *value_arr) LIB_DLL_EXPORTED
Force an immediate counter update and get a set of statistics for a specified device.
void opennsl_stat_value_t_init (opennsl_stat_value_t *stat_value) LIB_DLL_EXPORTED
Initialize a opennsl_stat_value_t data structure.
Detailed Description
Macro Definition Documentation
#define OPENNSL_STAT_GROUP_MODE_INGRESS 0x00000001
Stat Group Mode Ingress.
Definition at line 577 of file stat.h.
Typedef Documentation
typedef enum opennsl_stat_group_mode_attr_pkt_type_e opennsl_stat_group_mode_attr_pkt_type_t
Packet type related flex attributes values.
typedef struct opennsl_stat_group_mode_attr_selector_s opennsl_stat_group_mode_attr_selector_t
Stat Flex Group Attribute Selector.
typedef enum opennsl_stat_group_mode_attr_e opennsl_stat_group_mode_attr_t
Stat Group Mode Attribute Selectors.
typedef enum opennsl_stat_group_mode_e opennsl_stat_group_mode_t
Statistics Group Modes.
typedef enum opennsl_stat_object_e opennsl_stat_object_t
Ingress and Egress Statistics Accounting Objects.
typedef enum opennsl_stat_val_e opennsl_stat_val_t
Statistics counters.
Note: the following RFC 2465 MIBs are not supported:
snmpIpv6IfStatsInTooBigErrors, snmpIpv6IfStatsInNoRoutes, snmpIpv6IfStatsInUnknownProtos, snmpIpv6IfStatsInTruncatedPkts, snmpIpv6IfStatsInDelivers, snmpIpv6IfStatsOutRequests, snmpIpv6IfStatsOutFragOKs, snmpIpv6IfStatsOutFragFails, snmpIpv6IfStatsOutFragCreates, snmpIpv6IfStatsReasmReqds, snmpIpv6IfStatsReasmOKs, snmpIpv6IfStatsReasmFails,
typedef struct opennsl_stat_value_s opennsl_stat_value_t
Counter Statistics Values.
Enumeration Type Documentation
enum opennsl_stat_group_mode_attr_e
Stat Group Mode Attribute Selectors.
Enumerator:
opennslStatGroupModeAttrColor
Color Selector: Possible Value:opennslColorGreen|Yellow|REd or oxFFFFFFFF.
opennslStatGroupModeAttrFieldIngressColor
Field Ingress Color Selector: Possible Values:opennslColorGreen|Yellow|REd or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrIntPri
Internal Priority Selector: Possible Values: 0 to 15 or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrVlan
Vlan Type Selector: Possible Values: opennslStatGroupModeVlanAttr.
opennslStatGroupModeAttrOuterPri
Outer Vlan Priority Selector: Possible Values: 0 to 7 or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrInnerPri
Inner Vlan Priority Selector: Possible Values: 0 to 7 or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrPort
Logical Port Selector: Possible Values:<MaxLogicalPort> or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrTosDscp
Type Of Service Selector(DSCP : Differentiated services Code Point): Possible Values:<6b:TOS Val> or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrPktType
Packet Type Selector: Possible Values:<opennslStatGroupModeAttrPktType*>
opennslStatGroupModeAttrIngNetworkGroup
Ingress Network Group Selector: Possible Values:
or STAT_GROUP_MODE_ATTR_ALL_VALUES for all.
opennslStatGroupModeAttrDrop
Drop Selector: Possible Values:<0 or 1>
opennslStatGroupModeAttrPacketTypeIp
Ip Packet Selector: Possible Values:<0 or 1>
Definition at line 22 of file statX.h.
enum opennsl_stat_group_mode_attr_pkt_type_e
Packet type related flex attributes values.
Enumerator:
opennslStatGroupModeAttrPktTypeKnownL3UC
Known L3 Unicast Packet.
opennslStatGroupModeAttrPktTypeUnknownL3UC
Unknown L3 Unicast Packet.
opennslStatGroupModeAttrPktTypeKnownIPMC
Known IPMC Packet.
opennslStatGroupModeAttrPktTypeUnknownIPMC
Unknown IPMC Packet.
Definition at line 569 of file stat.h.
enum opennsl_stat_group_mode_e
Statistics Group Modes.
Enumerator:
opennslStatGroupModeSingle
A single counter used for all traffic types.
opennslStatGroupModeTrafficType
A dedicated counter per traffic type Unicast, multicast, broadcast.
Definition at line 594 of file stat.h.
enum opennsl_stat_object_e
Ingress and Egress Statistics Accounting Objects.
Enumerator:
opennslStatObjectIngL3Intf
Ingress L3 Interface Object.
opennslStatObjectEgrL3Intf
Egress L3 Interface Object.
Definition at line 579 of file stat.h.
enum opennsl_stat_val_e
Statistics counters.
Note: the following RFC 2465 MIBs are not supported:
snmpIpv6IfStatsInTooBigErrors, snmpIpv6IfStatsInNoRoutes, snmpIpv6IfStatsInUnknownProtos, snmpIpv6IfStatsInTruncatedPkts, snmpIpv6IfStatsInDelivers, snmpIpv6IfStatsOutRequests, snmpIpv6IfStatsOutFragOKs, snmpIpv6IfStatsOutFragFails, snmpIpv6IfStatsOutFragCreates, snmpIpv6IfStatsReasmReqds, snmpIpv6IfStatsReasmOKs, snmpIpv6IfStatsReasmFails,
Enumerator:
opennsl_spl_snmpIfInOctets
RFC 1213.
opennsl_spl_snmpIfInUcastPkts
RFC 1213.
opennsl_spl_snmpIfInNUcastPkts
RFC 1213.
opennsl_spl_snmpIfInDiscards
RFC 1213.
opennsl_spl_snmpIfInErrors
RFC 1213.
opennsl_spl_snmpIfInUnknownProtos
RFC 1213.
opennsl_spl_snmpIfOutOctets
RFC 1213.
opennsl_spl_snmpIfOutUcastPkts
RFC 1213.
opennsl_spl_snmpIfOutNUcastPkts
RFC 1213.
opennsl_spl_snmpIfOutDiscards
RFC 1213.
opennsl_spl_snmpIfOutErrors
RFC 1213.
opennsl_spl_snmpIfOutQLen
RFC 1213.
opennsl_spl_snmpIpInReceives
RFC 1213.
opennsl_spl_snmpIpInHdrErrors
RFC 1213.
opennsl_spl_snmpIpForwDatagrams
RFC 1213.
opennsl_spl_snmpIpInDiscards
RFC 1213.
opennsl_spl_snmpDot1dBasePortDelayExceededDiscards
RFC 1493.
opennsl_spl_snmpDot1dBasePortMtuExceededDiscards
RFC 1493.
opennsl_spl_snmpDot1dTpPortInFrames
RFC 1493.
opennsl_spl_snmpDot1dTpPortOutFrames
RFC 1493.
opennsl_spl_snmpDot1dPortInDiscards
RFC 1493.
opennsl_spl_snmpEtherStatsDropEvents
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsMulticastPkts
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsBroadcastPkts
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsUndersizePkts
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsFragments
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts64Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts65to127Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts128to255Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts256to511Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts512to1023Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts1024to1518Octets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsOversizePkts
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherRxOversizePkts
Rx component of snmpEtherStatsOversizePkts.
opennsl_spl_snmpEtherTxOversizePkts
Tx component of snmpEtherStatsOversizePkts.
opennsl_spl_snmpEtherStatsJabbers
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsOctets
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsPkts
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsCollisions
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsCRCAlignErrors
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsTXNoErrors
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsRXNoErrors
RFC 1757 (EtherStat)
opennsl_spl_snmpDot3StatsAlignmentErrors
RFC 2665.
opennsl_spl_snmpDot3StatsFCSErrors
RFC 2665.
opennsl_spl_snmpDot3StatsSingleCollisionFrames
RFC 2665.
opennsl_spl_snmpDot3StatsMultipleCollisionFrames
RFC 2665.
opennsl_spl_snmpDot3StatsSQETTestErrors
RFC 2665.
opennsl_spl_snmpDot3StatsDeferredTransmissions
RFC 2665.
opennsl_spl_snmpDot3StatsLateCollisions
RFC 2665.
opennsl_spl_snmpDot3StatsExcessiveCollisions
RFC 2665.
opennsl_spl_snmpDot3StatsInternalMacTransmitErrors
RFC 2665.
opennsl_spl_snmpDot3StatsCarrierSenseErrors
RFC 2665.
opennsl_spl_snmpDot3StatsFrameTooLongs
RFC 2665.
opennsl_spl_snmpDot3StatsInternalMacReceiveErrors
RFC 2665.
opennsl_spl_snmpDot3StatsSymbolErrors
RFC 2665.
opennsl_spl_snmpDot3ControlInUnknownOpcodes
RFC 2665.
opennsl_spl_snmpDot3InPauseFrames
RFC 2665.
opennsl_spl_snmpDot3OutPauseFrames
RFC 2665.
opennsl_spl_snmpIfHCInOctets
RFC 2233.
opennsl_spl_snmpIfHCInUcastPkts
RFC 2233.
opennsl_spl_snmpIfHCInMulticastPkts
RFC 2233.
opennsl_spl_snmpIfHCInBroadcastPkts
RFC 2233.
opennsl_spl_snmpIfHCOutOctets
RFC 2233.
opennsl_spl_snmpIfHCOutUcastPkts
RFC 2233.
opennsl_spl_snmpIfHCOutMulticastPkts
RFC 2233.
opennsl_spl_snmpIfHCOutBroadcastPckts
RFC 2233.
opennsl_spl_snmpIpv6IfStatsInReceives
RFC 2465.
opennsl_spl_snmpIpv6IfStatsInHdrErrors
RFC 2465.
opennsl_spl_snmpIpv6IfStatsInAddrErrors
RFC 2465.
opennsl_spl_snmpIpv6IfStatsInDiscards
RFC 2465.
opennsl_spl_snmpIpv6IfStatsOutForwDatagrams
RFC 2465.
opennsl_spl_snmpIpv6IfStatsOutDiscards
RFC 2465.
opennsl_spl_snmpIpv6IfStatsInMcastPkts
RFC 2465.
opennsl_spl_snmpIpv6IfStatsOutMcastPkts
RFC 2465.
opennsl_spl_snmpIfInBroadcastPkts
RFC 1573.
opennsl_spl_snmpIfInMulticastPkts
RFC 1573.
opennsl_spl_snmpIfOutBroadcastPkts
RFC 1573.
opennsl_spl_snmpIfOutMulticastPkts
RFC 1573.
opennsl_spl_snmpIeee8021PfcRequests
IEEE 802.1bb.
opennsl_spl_snmpIeee8021PfcIndications
IEEE 802.1bb.
snmpOpenNSLReceivedUndersizePkts
Broadcom-specific.
snmpOpenNSLTransmittedUndersizePkts
Broadcom-specific.
snmpOpenNSLIPMCBridgedPckts
Broadcom-specific.
snmpOpenNSLIPMCRoutedPckts
Broadcom-specific.
snmpOpenNSLIPMCInDroppedPckts
Broadcom-specific.
snmpOpenNSLIPMCOutDroppedPckts
Broadcom-specific.
snmpOpenNSLEtherStatsPkts1519to1522Octets
Broadcom-specific.
snmpOpenNSLEtherStatsPkts1522to2047Octets
Broadcom-specific.
snmpOpenNSLEtherStatsPkts2048to4095Octets
Broadcom-specific.
snmpOpenNSLEtherStatsPkts4095to9216Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts64Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts65to127Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts128to255Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts256to511Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts512to1023Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts1024to1518Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts1519to2047Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts2048to4095Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts4095to9216Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts64Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts65to127Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts128to255Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts256to511Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts512to1023Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts1024to1518Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts1519to2047Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts2048to4095Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts4095to9216Octets
Broadcom-specific.
snmpOpenNSLTxControlCells
Fabric TX Control cells counter.
(Broadcom-specific)
snmpOpenNSLTxDataCells
Fabric TX Data cell counter.
(Broadcom-specific)
snmpOpenNSLTxDataBytes
Fabric TX Data byte counter.
(Broadcom-specific)
snmpOpenNSLRxCrcErrors
Fabric RX CRC errors counter.
(Broadcom-specific)
snmpOpenNSLRxFecCorrectable
Fabric RX LFEC/FEC correctable error.
(Broadcom-specific)
snmpOpenNSLRxBecCrcErrors
Fabric RX BEC crc error.
(Broadcom-specific)
snmpOpenNSLRxDisparityErrors
Fabric RX 8b/10b disparity errors.
(Broadcom-specific)
snmpOpenNSLRxControlCells
Fabric RX Control cells counter.
(Broadcom-specific)
snmpOpenNSLRxDataCells
Fabric RX Data cell counter.
(Broadcom-specific)
snmpOpenNSLRxDataBytes
Fabric RX Data byte counter.
(Broadcom-specific)
snmpOpenNSLRxDroppedRetransmittedControl
Fabric RX dropped retransmitted control.
(Broadcom-specific)
snmpOpenNSLTxBecRetransmit
Fabric TX BEC retransmit.
(Broadcom-specific)
snmpOpenNSLRxBecRetransmit
Fabric RX BEC retransmit.
(Broadcom-specific)
snmpOpenNSLTxAsynFifoRate
Fabric TX Asyn fifo rate at units of 40 bits.
(Broadcom-specific)
snmpOpenNSLRxAsynFifoRate
Fabric RX Asyn fifo rate at units of 40 bits.
(Broadcom-specific)
snmpOpenNSLRxFecUncorrectable
Fabric RX LFEC/FEC uncorrectable erros.
(Broadcom-specific)
snmpOpenNSLRxBecRxFault
Fabric RX BEC RX fault.
(Broadcom-specific)
snmpOpenNSLRxCodeErrors
Fabric RX 8b/10b code errors.
(Broadcom-specific)
snmpOpenNSLRxLlfcPrimary
Fabric RX LLFC Primary.
(Broadcom-specific)
snmpOpenNSLRxLlfcSecondary
Fabric RX LLFC Secondary.
(Broadcom-specific)
snmpOpenNSLCustomReceive0
Broadcom-specific.
snmpOpenNSLCustomReceive1
Broadcom-specific.
snmpOpenNSLCustomReceive2
Broadcom-specific.
snmpOpenNSLCustomReceive3
Broadcom-specific.
snmpOpenNSLCustomReceive4
Broadcom-specific.
snmpOpenNSLCustomReceive5
Broadcom-specific.
snmpOpenNSLCustomReceive6
Broadcom-specific.
snmpOpenNSLCustomReceive7
Broadcom-specific.
snmpOpenNSLCustomReceive8
Broadcom-specific.
snmpOpenNSLCustomTransmit0
Broadcom-specific.
snmpOpenNSLCustomTransmit1
Broadcom-specific.
snmpOpenNSLCustomTransmit2
Broadcom-specific.
snmpOpenNSLCustomTransmit3
Broadcom-specific.
snmpOpenNSLCustomTransmit4
Broadcom-specific.
snmpOpenNSLCustomTransmit5
Broadcom-specific.
snmpOpenNSLCustomTransmit6
Broadcom-specific.
snmpOpenNSLCustomTransmit7
Broadcom-specific.
snmpOpenNSLCustomTransmit8
Broadcom-specific.
snmpOpenNSLCustomTransmit9
Broadcom-specific.
snmpOpenNSLCustomTransmit10
Broadcom-specific.
snmpOpenNSLCustomTransmit11
Broadcom-specific.
snmpOpenNSLCustomTransmit12
Broadcom-specific.
snmpOpenNSLCustomTransmit13
Broadcom-specific.
snmpOpenNSLCustomTransmit14
Broadcom-specific.
opennsl_spl_snmpDot3StatsInRangeLengthError
RFC 1284.
opennsl_spl_snmpDot3OmpEmulationCRC8Errors
RFC 4837.
opennsl_spl_snmpDot3MpcpRxGate
RFC 4837.
opennsl_spl_snmpDot3MpcpRxRegister
RFC 4837.
opennsl_spl_snmpDot3MpcpTxRegRequest
RFC 4837.
opennsl_spl_snmpDot3MpcpTxRegAck
RFC 4837.
opennsl_spl_snmpDot3MpcpTxReport
RFC 4837.
opennsl_spl_snmpDot3EponFecCorrectedBlocks
RFC 4837.
opennsl_spl_snmpDot3EponFecUncorrectableBlocks
RFC 4837.
snmpOpenNSLPonInDroppedOctets
Broadcom-specific.
snmpOpenNSLPonOutDroppedOctets
Broadcom-specific.
snmpOpenNSLPonInDelayedOctets
Broadcom-specific.
snmpOpenNSLPonOutDelayedOctets
Broadcom-specific.
snmpOpenNSLPonInDelayedHundredUs
Broadcom-specific.
snmpOpenNSLPonOutDelayedHundredUs
Broadcom-specific.
snmpOpenNSLPonInFrameErrors
Broadcom-specific.
snmpOpenNSLPonInOamFrames
Broadcom-specific.
snmpOpenNSLPonOutOamFrames
Broadcom-specific.
snmpOpenNSLPonOutUnusedOctets
Broadcom-specific.
snmpOpenNSLEtherStatsPkts9217to16383Octets
Broadcom-specific.
snmpOpenNSLReceivedPkts9217to16383Octets
Broadcom-specific.
snmpOpenNSLTransmittedPkts9217to16383Octets
Broadcom-specific.
snmpOpenNSLRxVlanTagFrame
Broadcom-specific.
snmpOpenNSLRxDoubleVlanTagFrame
Broadcom-specific.
snmpOpenNSLTxVlanTagFrame
Broadcom-specific.
snmpOpenNSLTxDoubleVlanTagFrame
Broadcom-specific.
snmpOpenNSLRxPFCControlFrame
PFC Receive Control Frame.
snmpOpenNSLTxPFCControlFrame
PFC Transmit Control Frame.
snmpOpenNSLRxPFCFrameXonPriority0
Receive PFC Frame Priority 0 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority1
Receive PFC Frame Priority 1 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority2
Receive PFC Frame Priority 2 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority3
Receive PFC Frame Priority 3 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority4
Receive PFC Frame Priority 4 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority5
Receive PFC Frame Priority 5 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority6
Receive PFC Frame Priority 6 XON to XOFF.
snmpOpenNSLRxPFCFrameXonPriority7
Receive PFC Frame Priority 7 XON to XOFF.
snmpOpenNSLRxPFCFramePriority0
Receive PFC Frame Priority 0.
snmpOpenNSLRxPFCFramePriority1
Receive PFC Frame Priority 1.
snmpOpenNSLRxPFCFramePriority2
Receive PFC Frame Priority 2.
snmpOpenNSLRxPFCFramePriority3
Receive PFC Frame Priority 3.
snmpOpenNSLRxPFCFramePriority4
Receive PFC Frame Priority 4.
snmpOpenNSLRxPFCFramePriority5
Receive PFC Frame Priority 5.
snmpOpenNSLRxPFCFramePriority6
Receive PFC Frame Priority 6.
snmpOpenNSLRxPFCFramePriority7
Receive PFC Frame Priority 7.
snmpOpenNSLTxPFCFramePriority0
Transmit PFC Frame Priority 0.
snmpOpenNSLTxPFCFramePriority1
Transmit PFC Frame Priority 1.
snmpOpenNSLTxPFCFramePriority2
Transmit PFC Frame Priority 2.
snmpOpenNSLTxPFCFramePriority3
Transmit PFC Frame Priority 3.
snmpOpenNSLTxPFCFramePriority4
Transmit PFC Frame Priority 4.
snmpOpenNSLTxPFCFramePriority5
Transmit PFC Frame Priority 5.
snmpOpenNSLTxPFCFramePriority6
Transmit PFC Frame Priority 6.
snmpOpenNSLTxPFCFramePriority7
Transmit PFC Frame Priority 7.
opennsl_spl_snmpFcmPortClass3RxFrames
RFC 4044.
opennsl_spl_snmpFcmPortClass3TxFrames
RFC 4044.
opennsl_spl_snmpFcmPortClass3Discards
RFC 4044.
opennsl_spl_snmpFcmPortClass2RxFrames
RFC 4044.
opennsl_spl_snmpFcmPortClass2TxFrames
RFC 4044.
opennsl_spl_snmpFcmPortClass2Discards
RFC 4044.
opennsl_spl_snmpFcmPortInvalidCRCs
RFC 4044.
opennsl_spl_snmpFcmPortDelimiterErrors
RFC 4044.
snmpOpenNSLSampleIngressPkts
Total number of packets eligible to be sampled by Ingress Sampler.
(Broadcom-specific)
snmpOpenNSLSampleIngressSnapshotPkts
Total number of eligible packets when the last packet was sampled by Ingress sampler.
(Broadcom-specific)
snmpOpenNSLSampleIngressSampledPkts
Total number of packets sampled by Ingress sampler.
(Broadcom-specific)
snmpOpenNSLSampleFlexPkts
Total number of packets eligible to be sampled by Flex sampler enabled by IFP ingress sampling policy action.
(Broadcom-specific)
snmpOpenNSLSampleFlexSnapshotPkts
Total number of eligible packets when the last packet was sampled by Flex sampler enabled by IFP ingress sampling policy action.
(Broadcom-specific)
snmpOpenNSLSampleFlexSampledPkts
Total number of packets sampled by Flex sampler enabled by IFP ingress sampling policy action.
(Broadcom-specific)
snmpOpenNSLEgressProtectionDataDrop
Egress Protection data drop in EPIPE.
(Broadcom-specific)
snmpOpenNSLTxE2ECCControlFrames
Total number of End to End Congestion Control(E2E-CC) Head of line(HOL) packets or DMVoQ flow control packets transmitted on each of the ports.
(Broadcom-specific)
snmpOpenNSLE2EHOLDropPkts
Total number of packets dropped due to E2EHOL (End to End Head of Line) drop status.
(Broadcom-specific)
opennsl_spl_snmpEtherStatsTxCRCAlignErrors
RFC 1757 (EtherStat)
opennsl_spl_snmpEtherStatsTxJabbers
RFC 1757 (EtherStat)
opennsl_spl_snmpValCount
Definition at line 47 of file stat.h.
Function Documentation
int opennsl_stat_clear (int unit, opennsl_port_t port)
Clear the port-based statistics for the indicated device port.
Description
Set all counters to zero to the specified port.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
Return values
OPENNSL_E_NONE Success
OPENNSL_E_INTERNAL Device access failure
Referenced by main().
int opennsl_stat_clear_single (int unit, opennsl_port_t port, opennsl_stat_val_t type)
Clear specific statistics for a port from the device.
Description
Set all counters to zero for a specific statistics type of the specified port.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
type [IN] SNMP statistics type defined in opennsl_stat_val_t
Return values
OPENNSL_E_NONE Success.
OPENNSL_E_PARAM Illegal parameter.
OPENNSL_E_BADID Illegal port number.
OPENNSL_E_INTERNAL Device access failure.
OPENNSL_E_UNAVAIL Counter/variable is not implemented on this current chip.
int opennsl_stat_custom_group_create (int unit, uint32 mode_id, opennsl_stat_object_t object, uint32 * stat_counter_id, uint32 * num_entries)
Associate an accounting object to customized group mode.
Description
This API Associate an accounting object to customized group mode and make system ready for further stat collection action.
Parameters
unit [IN] Unit number.
mode_id [IN] Created Mode Identifier for Stat Flex Group Mode
object [IN] Accounting Object
stat_counter_id [OUT]
num_entries [OUT] Number of Counter entries created
Return values
OPENNSL_E_XXX
int opennsl_stat_get (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint64 * value)
Get the specified statistics from the device.
Description
The native statistics are 64-bits wide; use opennsl_stat_get32() for 32-bit statistics. Some counters are implemented on a given port only when it is operating in a specific mode, for example, 10 or 100, and not 1000 Mbps. If the counter is not implemented on the specified port, or on the port given its current operating mode, OPENNSL_E_UNAVAIL is returned.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
type [IN] SNMP statistics type defined in opennsl_stat_val_t
value [OUT] Counter value
Return values
OPENNSL_E_NONE Success.
OPENNSL_E_PARAM Illegal parameter.
OPENNSL_E_BADID Illegal port number.
OPENNSL_E_INTERNAL Device access failure.
OPENNSL_E_UNAVAIL Counter/variable is not implemented on this current chip.
Referenced by main().
int opennsl_stat_get32 (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint32 * value)
Get the specified statistics from the device.
Description
The native statistics are 64-bits wide; use opennsl_stat_get32() for 32-bit statistics. Some counters are implemented on a given port only when it is operating in a specific mode, for example, 10 or 100, and not 1000 Mbps. If the counter is not implemented on the specified port, or on the port given its current operating mode, OPENNSL_E_UNAVAIL is returned.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
type [IN] SNMP statistics type defined in opennsl_stat_val_t
value [OUT] Counter value
Return values
OPENNSL_E_NONE Success.
OPENNSL_E_PARAM Illegal parameter.
OPENNSL_E_BADID Illegal port number.
OPENNSL_E_INTERNAL Device access failure.
OPENNSL_E_UNAVAIL Counter/variable is not implemented on this current chip.
int opennsl_stat_group_create (int unit, opennsl_stat_object_t object, opennsl_stat_group_mode_t group_mode, uint32 * stat_counter_id, uint32 * num_entries)
Create Counter Entries group for given accounting object.
Description
This API will reserve HW counter resources as per given group mode and Accounting object and make system ready for further stat collection action based on stat counter ID. This API will be deprecated in the second half of 2016. opennsl_stat_custom_group_create (after creating mode id using opennsl_stat_group_mode_id_config_create API) should be used to create stat groups. However opennsl_stat_group_destroy will continue to be used to destroy groups created using the new opennsl_stat_custom_group_create API.
Parameters
unit [IN] Unit number.
object [IN] Accounting Object
group_mode [IN]
stat_counter_id [OUT]
num_entries [OUT] Number of Counter entries created
Return values
OPENNSL_E_XXX
int opennsl_stat_group_destroy (int unit, uint32 stat_counter_id)
Destroy counter Entries group.
Description
This API will release HW counter resources as per given counter ID and makes system unavailable for any further stat collection action based on stat counter id. Tomahawk supports stat_counter_id range from 1 to 0x26000.
Parameters
unit [IN] Unit number.
stat_counter_id [IN] Counter Mode ID
Return values
OPENNSL_E_XXX
void opennsl_stat_group_mode_attr_selector_t_init (opennsl_stat_group_mode_attr_selector_t * attr_selector)
Initialize an attribute selector of Stat Flex Group Mode.
Description
This API create Customized Stat Group mode for given Counter Attributes and make system ready for attaching created mode id to different a/c objects.
Parameters
attr_selector [IN,OUT] Attribute Selector for Stat Flex Group Mode
Return values
OPENNSL_E_XXX
int opennsl_stat_group_mode_id_create (int unit, uint32 flags, uint32 total_counters, uint32 num_selectors, opennsl_stat_group_mode_attr_selector_t * attr_selectors, uint32 * mode_id)
Create Customized Stat Group mode for given Counter Attributes In network switch, OAM LM is supported through Flex Counters, When OPENNSL_STAT_GROUP_MODE_CAPABILITY_OAM flag is passed along with OPENNSL_STAT_GROUP_MODE_INGRESS or OPENNSL_STAT_GROUP_MODE_EGRESS, it instructs the API to create a stat group suitable for OAM.
In network switch, the packet cfi_pri offset map of Vlan Flow Counters is supported through this function to get the mode_id. And use this mode_id to create the customized group mode by opennsl_stat_custom_group_create. Counters with same counter_offset and with same attribute type but different attributes values are counted whenever either of the value(s) are true whereas with different attribute types the counter is incremented only when all of the attributes satisfy with their respective values. This API will be deprecated in the second half of 2016. stats mode id should be created using opennsl_stat_group_mode_id_config_create API.
Description
This API create Customized Stat Group mode for given Counter Attributes and make system ready for attaching created mode id to different a/c objects.
Parameters
unit [IN] Unit number.
flags [IN] STAT_GROUP_MODE_* flags (INGRESS/EGRESS)
total_counters [IN] Total Counters for Stat Flex Group Mode
num_selectors [IN] Number of Selectors for Stat Flex Group Mode
attr_selectors [IN] Attribute Selectors for Stat Flex Group Mode
mode_id [OUT] Created Mode Identifier for Stat Flex Group Mode
Return values
OPENNSL_E_XXX
int opennsl_stat_group_mode_id_destroy (int unit, uint32 mode_id)
Destroys Customized Group mode.
Description
This API Destroys created Customized Group mode.
Parameters
unit [IN] Unit number.
mode_id [IN] Created Mode Identifier for Stat Flex Group Mode
Return values
OPENNSL_E_XXX
int opennsl_stat_init (int unit)
Initialize the OPENNSL statistics module.
Description
Initialize all counters to zero and start the counter collection.
Parameters
unit [IN] Unit number.
Return values
OPENNSL_E_NONE Success
OPENNSL_E_INTERNAL Device access failure
Referenced by main().
int opennsl_stat_multi_get (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t * stat_arr, uint64 * value_arr)
Get the specified statistics from the device.
Description
This API will retrieve a set of statistic values of the types specified in the stat_arr array. The number of values in the stat_arr array and the available positions in the value_arr array must match the number given in the nstat argument. 64-bit values may be truncated to fit into a 32-bit array for opennsl_stat_multi_get32.
Parameters
unit [IN] Unit number.
port [IN] <UNDEF>
nstat [IN] Number of elements in stat array
stat_arr [IN] Array of SNMP statistics types defined in opennsl_stat_val_t
value_arr [OUT] Collected 64-bit or 32-bit statistics values
Return values
OPENNSL_E_xxx
Referenced by main().
int opennsl_stat_multi_get32 (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t * stat_arr, uint32 * value_arr)
Get the specified statistics from the device.
Description
This API will retrieve a set of statistic values of the types specified in the stat_arr array. The number of values in the stat_arr array and the available positions in the value_arr array must match the number given in the nstat argument. 64-bit values may be truncated to fit into a 32-bit array for opennsl_stat_multi_get32.
Parameters
unit [IN] Unit number.
port [IN] <UNDEF>
nstat [IN] Number of elements in stat array
stat_arr [IN] Array of SNMP statistics types defined in opennsl_stat_val_t
value_arr [OUT] Collected 64-bit or 32-bit statistics values
Return values
OPENNSL_E_xxx
int opennsl_stat_sync (int unit)
Synchronize software counters with hardware.
Description
Force an immediate counter update. Ensures that all hardware counter activity prior to the call to opennsl_stat_sync() is reflected in all opennsl_stat_get() calls that come after the call to opennsl_stat_sync().
Parameters
unit [IN] Unit number.
Return values
OPENNSL_E_NONE Success
OPENNSL_E_TIMEOUT Device response time exceeds limit
OPENNSL_E_DISABLED Unit's counter disabled
Referenced by main().
int opennsl_stat_sync_get32 (int unit, opennsl_port_t port, opennsl_stat_val_t type, uint32 * value)
Force an immediate counter update and get statistics for a specified device.
Note: If opennsl_stat_sync_get was continuously called for a counter, the corresponding rate calculated with CLI show counter will be incorrect.
Description
Same as opennsl_stat_get(), value returned is per-port software accumulated counter synced with the hardware counter.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
type [IN] SNMP statistics type defined in opennsl_stat_val_t
value [OUT] Counter value
Return values
OPENNSL_E_NONE Success.
OPENNSL_E_PARAM Illegal parameter.
OPENNSL_E_BADID Illegal port number.
OPENNSL_E_INTERNAL Device access failure.
OPENNSL_E_UNAVAIL Counter/variable is not implemented on this current chip.
int opennsl_stat_sync_multi_get32 (int unit, opennsl_port_t port, int nstat, opennsl_stat_val_t * stat_arr, uint32 * value_arr)
Force an immediate counter update and get a set of statistics for a specified device.
Description
Same as opennsl_stat_multi_get(), value returned is per-port software accumulated counter synced with the hardware counter.
Parameters
unit [IN] Unit number.
port [IN] Zero-based device or logical port number
nstat [IN] Number of elements in stat array
stat_arr [IN] Array of SNMP statistics types defined in
value_arr [OUT] Collected statistics values
Return values
OPENNSL_E_NONE Success.
OPENNSL_E_PARAM Illegal parameter.
OPENNSL_E_BADID Illegal port number.
OPENNSL_E_INTERNAL Device access failure.
OPENNSL_E_UNAVAIL Counter/variable is not implemented on this current chip.
void opennsl_stat_value_t_init (opennsl_stat_value_t * stat_value)
Initialize a opennsl_stat_value_t data structure.
Description
This API initializes the opennsl_stat_value_t data structure.
Parameters
stat_value [IN,OUT] pointer to the opennsl_stat_value_t data to be initialized.
Return values
NONE