OpenNSL API Guide and Reference Manual: /tmp/ec11211217_RELEASE_INT_OPENNSL_3.3_3.3.0.2-gto-trident-brl20/opennsl/packages/common/docs/doxygen/opennsl_api.dox File Reference
/tmp/ec11211217_RELEASE_INT_OPENNSL_3.3_3.3.0.2-gto-trident-brl20/opennsl/packages/common/docs/doxygen/opennsl_api.dox File Reference
Functions
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 a VRF must be
specified At the end of a MPLS
the IPv4 or IPv6 DIP lookup is
qualified by VRF associated
with the L3 VPN page
OPENNSL_STACK_MANAGEMENT_OVERVIEW
Multi device Stack Control
APIs Network switches can act
in a stand alone manner or be
part of a larger distributed
switching system Such systems
may be simply a small number
of switching devices within a
single box or a larger number
of switching devices across
multiple stacked boxes or in a
chassis In each of these each
switch device must be
programmed with its address in
the larger Gigabit Ethernet (GbE) or Ten Gigabit Ethernet(XE) ports) and one or more HiGig ports.\li Some devices may have gigabit ports that are capable of being put into a stack mode where each packet sent or received with an extra stack tag that provides stack wide addressing information.This type of stack port is called an SL stack port or front-panel stack port.SL stack ports can be run in either simplex or duplex mode.Simplex stack ports transmit to one remote device and receives from another.Full connectivity in the stack requires that all stack ports in the system form a non-redundant ring.Simplex stack rings require that the count of systems in the ring be programmed into each stack port.A ring of systems can be const ructed with only a single stack port on each system
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS header (label PUSH operation).IPv4 and IPv6 packets can be directed into an MPLS tunnel based on the DIP lookup.Along the path of the MPLS tunnel
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS port (see description below).The VPN ID is used to qualify MAC DA lookups in VPLS.For VPWS
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Service (VPWS) and point-to-multipoint Virtual Private LAN Service(VPLS) Ethernet transport services.In VPWS
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 a VRF must be
specified At the end of a MPLS
the IPv4 or IPv6 DIP lookup is
qualified by VRF associated
with the L3 VPN page
OPENNSL_STACK_MANAGEMENT_OVERVIEW
Multi device Stack Control
APIs Network switches can act
in a stand alone manner or be
part of a larger distributed
switching system Such systems
may be simply a small number
of switching devices within a
single box or a larger number
of switching devices across
multiple stacked boxes or in a
chassis In each of these each
switch device must be
programmed with its address in
the larger system (called a module identifier or module ID) and have some means of directing traffic to other devices in the system.This topology information may be statically defined or dynamically determined by using stacking software.These defined API routines are the building blocks to set the system wide addressing and topology information.Some fabric switches provide a mechanism called module mapping that allows up to 128 module identifiers to be used in a system.There are two general types of stack ports that are supported.\li HiGig ports are dedicated 10 gigabit/second stack ports.These ports are found on most switch devices.There are dedicated fabric switches that consist only of HiGig ports as well as network switches that contain one or more front-panel ports(which can be Fast Ethernet(FE)
Variables
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS APIs
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 a VRF must be
specified At the end of a MPLS
the IPv4 or IPv6 DIP lookup is
qualified by VRF associated
with the L3 VPN page
OPENNSL_STACK_MANAGEMENT_OVERVIEW
Multi device Stack Control
APIs Network switches can act
in a stand alone manner or be
part of a larger distributed
switching system Such systems
may be simply a small number
of switching devices within a
single box or a larger number
of switching devices across
multiple stacked boxes or in a
chassis In each of these cases
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two categories
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain However
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or L3
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label PHP
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation point
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical ports
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a pseudowire
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label PUSH
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 a VRF must be
specified At the end of a MPLS
the IPv4 or IPv6 DIP lookup is
qualified by VRF associated
with the L3 VPN page
OPENNSL_STACK_MANAGEMENT_OVERVIEW
Multi device Stack Control
APIs Network switches can act
in a stand alone manner or be
part of a larger distributed
switching system Such systems
may be simply a small number
of switching devices within a
single box or a larger number
of switching devices across
multiple stacked boxes or in a
chassis In each of these each
switch device must be
programmed with its address in
the larger Gigabit but a
single link failure can
disrupt the entire ring An SL
stack port in duplex mode
transmits and receives with a
single remote system to build
a ring of stacked two stack
ports are required
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label SWAP
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 a VRF must be
specified At the end of a MPLS
the IPv4 or IPv6 DIP lookup is
qualified by VRF associated
with the L3 VPN page
OPENNSL_STACK_MANAGEMENT_OVERVIEW
Multi device Stack Control
APIs Network switches can act
in a stand alone manner or be
part of a larger distributed
switching system Such systems
may be simply a small number
of switching devices within a
single box or a larger number
of switching devices across
multiple stacked boxes or in a
chassis In each of these each
switch device must be
programmed with its address in
the larger Gigabit but a
single link failure can
disrupt the entire ring An SL
stack port in duplex mode
transmits and receives with a
single remote system to build
a ring of stacked systems
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS tunnel
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a VLAN
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In VPLS
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type or a VPN is similar
to a which identifies a group
of physical ports to be
included in a broadcast domain
instead of physical a VPLS VPN
identifies a group of virtual
ports to be included in a
broadcast domain In the MPLS a
virtual port is called an MPLS
a VPN consists of two MPLS
ports Packets arriving on one
MPLS port are sent directly
out the other MPLS port L3
VPNs are used to identify
virtual a routing table When
creating an L3 VPN
page OPENNSL_MPLS_OVERVIEW
MPLS management MPLS support
can be broken down into two
Layer and Layer MPLS L2 MPLS
consists of point to point
Virtual Private Wire Ethernet
frames are mapped into a MPLS
pseudowire based on incoming
port plus packet header
information At the end of a
forwarding of Ethernet frames
after MPLS decapsulation is
based on the MPLS label lookup
In Ethernet frames of interest
are also identified by
incoming port plus packet
header information Ethernet
frames are switched into one
or more MPLS pseudowires based
on the MAC DA lookup At the
end of a frames again are
switched based on MAC DA
lookup L3 MPLS deals with the
establishment of MPLS tunnels
At the MPLS tunnel initiation
packets entering the tunnel
are encapsulated with an MPLS
MPLS label and POP operations
are supported At the end of an
MPLS forwarding of IPv4 and
IPv6 packets is based on DIP
lookup Virtual routing tables
are supported for the DIP
lookup In the MPLS the concept
of VPN is introduced A VPN can
be of type VPWS
Function Documentation
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS the IPv4 or IPv6 DIP lookup is qualified by VRF associated with the L3 VPN page OPENNSL_STACK_MANAGEMENT_OVERVIEW Multi device Stack Control APIs Network switches can act in a stand alone manner or be part of a larger distributed switching system Such systems may be simply a small number of switching devices within a single box or a larger number of switching devices across multiple stacked boxes or in a chassis In each of these each switch device must be programmed with its address in the larger Gigabit Ethernet (GbE) const
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS header (label PUSH operation)
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS port (see description below)
Referenced by add_to_l2_table(), example_bst_default_profile_set(), example_knet_database_show(), example_knet_database_update(), example_knet_intf_create(), example_l2_addr_add(), example_linux_interface_create(), example_port_default_config(), example_switch_default_vlan_config(), and main().
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Service (VPWS)
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS the IPv4 or IPv6 DIP lookup is qualified by VRF associated with the L3 VPN page OPENNSL_STACK_MANAGEMENT_OVERVIEW Multi device Stack Control APIs Network switches can act in a stand alone manner or be part of a larger distributed switching system Such systems may be simply a small number of switching devices within a single box or a larger number of switching devices across multiple stacked boxes or in a chassis In each of these each switch device must be programmed with its address in the larger system (called a module identifier or module ID)
Referenced by example_ip_config().
Variable Documentation
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS APIs
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS the IPv4 or IPv6 DIP lookup is qualified by VRF associated with the L3 VPN page OPENNSL_STACK_MANAGEMENT_OVERVIEW Multi device Stack Control APIs Network switches can act in a stand alone manner or be part of a larger distributed switching system Such systems may be simply a small number of switching devices within a single box or a larger number of switching devices across multiple stacked boxes or in a chassis In each of these cases
Definition at line 524 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two categories
Definition at line 484 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain However
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or L3
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label PHP
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation point
Definition at line 492 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical ports
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a pseudowire
Definition at line 492 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label PUSH
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS the IPv4 or IPv6 DIP lookup is qualified by VRF associated with the L3 VPN page OPENNSL_STACK_MANAGEMENT_OVERVIEW Multi device Stack Control APIs Network switches can act in a stand alone manner or be part of a larger distributed switching system Such systems may be simply a small number of switching devices within a single box or a larger number of switching devices across multiple stacked boxes or in a chassis In each of these each switch device must be programmed with its address in the larger Gigabit but a single link failure can disrupt the entire ring An SL stack port in duplex mode transmits and receives with a single remote system to build a ring of stacked two stack ports are required
Definition at line 570 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label SWAP
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS the IPv4 or IPv6 DIP lookup is qualified by VRF associated with the L3 VPN page OPENNSL_STACK_MANAGEMENT_OVERVIEW Multi device Stack Control APIs Network switches can act in a stand alone manner or be part of a larger distributed switching system Such systems may be simply a small number of switching devices within a single box or a larger number of switching devices across multiple stacked boxes or in a chassis In each of these each switch device must be programmed with its address in the larger Gigabit but a single link failure can disrupt the entire ring An SL stack port in duplex mode transmits and receives with a single remote system to build a ring of stacked systems
Definition at line 570 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 a VRF must be specified At the end of a MPLS tunnel
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a VLAN
Definition at line 504 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type VPLS
Definition at line 492 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type or a VPN is similar to a which identifies a group of physical ports to be included in a broadcast domain instead of physical a VPLS VPN identifies a group of virtual ports to be included in a broadcast domain In the MPLS a virtual port is called an MPLS a VPN consists of two MPLS ports Packets arriving on one MPLS port are sent directly out the other MPLS port L3 VPNs are used to identify virtual a routing table When creating an L3 VPN
Definition at line 524 of file opennsl_api.dox.
page OPENNSL_MPLS_OVERVIEW MPLS management MPLS support can be broken down into two Layer and Layer MPLS L2 MPLS consists of point to point Virtual Private Wire Ethernet frames are mapped into a MPLS pseudowire based on incoming port plus packet header information At the end of a forwarding of Ethernet frames after MPLS decapsulation is based on the MPLS label lookup In Ethernet frames of interest are also identified by incoming port plus packet header information Ethernet frames are switched into one or more MPLS pseudowires based on the MAC DA lookup At the end of a frames again are switched based on MAC DA lookup L3 MPLS deals with the establishment of MPLS tunnels At the MPLS tunnel initiation packets entering the tunnel are encapsulated with an MPLS MPLS label and POP operations are supported At the end of an MPLS forwarding of IPv4 and IPv6 packets is based on DIP lookup Virtual routing tables are supported for the DIP lookup In the MPLS the concept of VPN is introduced A VPN can be of type VPWS
Definition at line 504 of file opennsl_api.dox.